// Exploration artwork and arcane traitstone master. Run with ART_MANIFEST=exploreAssets.mjs.
// The 21 colorways are derived from the neutral master by processExplore.py.
export const ASSETS = {
  'stone-arcane-master': {
    size: '1024x1024', background: 'transparent', longest: 512, pad: 0.035,
    out: 'artifacts/art-gen/processed/stone-arcane-master.webp',
    prompt: `Production inventory item for a polished fantasy match-three RPG. One isolated advanced magical crystal gemstone on genuine transparent alpha, centered with 12% clear padding. No background, no floor or pedestal, no cast shadow, no text or symbols.
Style reference described precisely: the existing lower-tier material is a dark translucent glossy pear-shaped faceted sapphire, realistic hand-painted 3D gemstone rendering, very dark interior cavities, broad clean polygonal facets, cold white specular glints from upper-left, clean cutout edges. Match this restrained existing item family, NOT a cartoon, vector icon, ornament or golden badge.
Create the next evolution of that gemstone: an imposing double-terminated hexagonal crystal with a broad multifaceted central body and two smaller integrated shoulder facets at its base. One cohesive crystal specimen, not scattered pieces. A strong upright diamond-like six-sided silhouette, taller than wide, subtly three-quarter view, front faces readable at 64 pixels. More refined and powerful than a simple teardrop sapphire without excessive decoration. An internal central split divides left and right crystal chambers, ready for later dual-color grading. Elegant beveled planes and a few fine refractive interior lines, subtle luminous core, rich contrast. No metal casing, no gold, no wire, no ring, no engraved runes, no particles, no exterior aura.
IMPORTANT neutral master for palette grading: ONLY colorless smoky quartz, charcoal gray cavities, silver-gray facets and pure white highlights, absolutely no colored tint. Keep most front facets medium-gray so they can be tinted vividly later; reserve near black for small cavities. Transparent background, never a painted checkerboard. Exactly one full crystal, no cropping.`,
  },
  'explore-relic-landscape': {
    size: '1536x1024', background: 'opaque', longest: 1536, pad: 0,
    out: 'game-assets/bundled/meta/explore/relic-landscape.webp',
    prompt: `Production environment background for a mature fantasy RPG kingdom expedition interface, not a screenshot or UI mockup. A magnificent forgotten sanctuary on a mountainside above a blue mist valley at twilight. Foreground ancient slate stairs and fractured stone terraces lead toward a monumental circular relic doorway standing at the right third, half buried in weathered stone architecture; faint cyan light breathes from its interior. Small translucent blue and amethyst crystal outcrops naturally embedded in the lower stone terraces, one warm amber lantern near the steps. Distant layered ridgelines and pale sky light create convincing depth. Old architecture has restrained pale bronze inlays, NOT baroque gold filigree. Rich painterly game key art, carefully shaped realistic stone, quiet wonder, serious premium fantasy mood, no cartoon.
Wide landscape composition. Keep the central and left-center areas low-detail with blue atmospheric depth so translucent game panels can sit on top; put architectural detail and visual interest at the far right and outer edges. The upper half has soft muted dusk blue and violet, lower edge dark slate. Visible scenic contrast and light accents, not a nearly black image, no busy texture across the whole frame. Balanced teal-blue, slate-violet and a tiny amber accent, cinematic light shafts, subtle aerial perspective. No people, no creatures, no battle, no UI, no letters, no numbers, no symbols resembling text, no logos, no watermark, no border.`,
  },
  'explore-difficulty-sigil': {
    size: '1024x1024', background: 'transparent', longest: 320, pad: 0.025,
    out: 'game-assets/bundled/meta/explore/difficulty-sigil.webp',
    prompt: `One circular ancient exploration relic for a mature fantasy game interface, isolated on genuine transparent alpha. A slim elegant compass-like stone and brushed pale bronze ring, viewed perfectly front-on, with four modest pointed compass tips at the cardinal directions. Dark slate stone, subtle pale bronze bevels, tiny inset cool blue crystal at the bottom and two at the sides. Premium hand-painted realistic game item, clean readable silhouette, restrained detail. Slight weathering, beautiful edge highlights, NOT heavy baroque ornament or a shiny gold medal. Outer diameter occupies 82 percent of the square image. The inner circular opening occupies 68 percent of the ring diameter and MUST be entirely empty and transparent so a difficulty number can later be placed there. Very thin delicate inner ring, no central object, no background disk, no backplate, no ribbon, no shield, no swords, no text, no numbers, no letter-like runes, no glow haze, no particles, no cast shadow. Symmetrical quiet silhouette with a few crafted facets, not a mandala. No mockup, no background and no painted checkerboard.`,
  },
};
