export const ASSETS = {
  'treasure-shapes-v6': {
    size: '1536x1024', background: 'opaque',
    prompt: `Create a clean production game sprite sheet of EXACTLY THREE distinct metal treasure tokens on a perfectly flat solid dark navy #101722 backdrop. One horizontal row, each isolated in its own equal-width third, centers at x=16.7%,50%,83.3%, y=50%. Maximum object width 72% of its third; generous empty space around every object. Entire silhouettes visible, no cast shadows on background. No text or labels.
Mature restrained fantasy match-3 art, soft diffuse lighting, simple smooth matte metal, shallow dimensional thickness, mostly front-facing readable silhouettes. No cartoon outlines, no cute proportions, no photoreal surface grain. Unified lighting from upper left. At 48 pixels each token must be identified by silhouette alone, no dependence on hue.
LEFT: dark reddish COPPER rounded-SQUARE coin/token, NOT a circle and NOT a diamond. Width and height similar with short gently rounded corners and clearly straight sides. A small central square punched hole, background visible through it, the only interior detail. Mostly flat deep brick-copper face #884B38, narrow low-contrast bevel. Dark but clearly visible against navy. No decorative border ring.
CENTER: light SILVER vertically elongated HEXAGON coin. Six clearly defined edges, pointed top and bottom, width about 75% of height. Entirely plain face with NO emblem, NO star and NO central hole. Light cool silver #D6DEE2, gentle soft shading, no brilliant white rim. Keep most of face consistently light, no dark half or heavy metallic reflections. Thin understated edge. Its tall angular outline is unmistakably different from the square on the left.
RIGHT: a GOLD INGOT with a broad horizontal TRAPEZOID silhouette, width roughly 1.5 times height. Classic simple cast bullion bar, not Chinese boat-shaped sycee. Flat broad blank top face, very shallow thickness, angled short sidewalls, overall low horizontal block silhouette. Rich ochre-yellow gold #BA902C at clearly intermediate lightness, significantly darker than silver and lighter than copper. Not orange or brown. No stamp, emblem, star, linework or rings.
STRICT DESIGN RULE: no shared repeating central symbols; no stars anywhere. Separate three average grayscale brightness bands: copper approximately 80/255, gold 145/255, silver 205/255. Low INTERNAL contrast and restrained broad shading, strong BETWEEN-TYPE lightness differences. No specular streaks, sparkles, scratches, inscriptions, engraving, patina, noise, or layered rims. Each object should read as a simple solid colored silhouette rather than a decorative medallion. Equal perceived visual weight, generous breathing room. Calm clean premium fantasy game assets, not flat vector clipart.`
  }
};
