export const ASSETS = {
  'treasure-coins-v8': {
    size: '1536x1024', background: 'opaque',
    prompt: `Make a production-quality 3-item sprite sheet in the EXACT ART DIRECTION of these existing match-3 game pieces: game-assets/bundled/gems/brown.png is a dark amber shield-shaped thick faceted token bearing ONE simple raised mountain pictogram; blue.png is a blue thick hexagonal token bearing ONE smooth spiral pictogram; yellow.png is a rich golden sun-shaped token bearing ONE central golden bead. These pieces are painterly high-end fantasy GAME ART with distinctive silhouettes, chunky forms, simplified beautiful reflections, sculpted raised symbols, crisp alpha-like contours, rich saturation, and coherent upper-left highlights. The treasure pieces must look as if they are from THAT SAME GAME rather than realistic blank coins or industrial bullion. Artwork is isolated on uniform dark navy #101722 background for clean cutout.
Draw EXACTLY THREE separate wealth-themed collectible game tokens in one horizontal row with centers at x=16.7%,50%,83.3%, all at center height. Equal bold visual weight and overall apparent size, fully isolated in their own thirds. Each piece occupies around 70% of its column width and 55% canvas height, with no contact or overlap. All pieces have shared fantasy sculpting, consistent lighting and thickness, ONE peripheral bevel and ONE big icon each. At board scale icons are readable immediately, forms are noticeably different, but their shared material finish and shading clearly unifies the set. Do NOT show a plain circle or three copies of the same star.
LEFT, COPPER: warm deep reddish-copper sculpted coin-like game token with compact 8-sided softly chamfered perimeter, wider than tall is NOT allowed, about equal width and height. Single centered iconic relief: a simple RAISED SQUARE inside a CIRCLE, like a classical coin motif, occupying 32% of the face, raised warm light copper and not a hollow square punched through. Color medium-dark warm red copper with one simple restrained broad warm highlight.
MIDDLE, SILVER: cool very light argent-silver sculpted coin-like token with softly rounded 6-sided perimeter whose top and bottom corners are gently clipped, same size as copper. Single centered iconic relief: ONE smooth simple crescent moon motif occupying 38% face, blue-gray silver raised metal for readability. Face in bright pale clean silver with broad cool highlights and deeper steel on outer side walls; remains brighter overall than gold and copper.
RIGHT, GOLD: rich yellow-gold sculpted coin-like token with 10 broad gently scalloped sides, recognizable as a precious coin rather than a bar; same size as copper and silver. Single centered iconic relief: ONE simple diamond-shaped jewel silhouette cast in gold occupying 38% face, not an actual colored gem. Gold face medium-bright clear yellow rich gold, brighter than copper, darker than silver.
These three pieces should be playful enough to look like REAL MATCH-3 GAME PIECES but NOT childish or cartoonish. Not photo, not plain unmarked real-world coins, not an abstract flat vector UI, not ornate jewelry. No dust, scratches, noise, tiny detailing, little trim stripes, letters, currency signs, star shapes, secondary emblems, patterned rims, sparkles, halos, wild highlights. Clear big iconic shapes with a premium cohesive fantasy game-rendered finish. Silhouettes and central motifs remain distinguishable in a GRAYSCALE 8x8 board and at 60px wide. Ignore technical source path names: they are design style descriptions, not text to render. No text or labels.`
  }
};
