export const ASSETS = {
  'treasure-coins-contrast-v5': {
    size: '1536x1024',
    background: 'opaque',
    prompt: `Game sprite sheet containing EXACTLY THREE separate coins, a SINGLE HORIZONTAL ROW, on a perfectly flat solid navy background #101722. No text, no labels, no other objects, no ground, no drop shadows outside silhouettes. Landscape canvas with each coin centered in its own equal-width third, at least 8 percent empty margin from each third's boundaries. All coins same size, occupying 70 percent of their column width and centered vertically. Coin centers at 16.7, 50, 83.3 percent canvas width. Entire silhouettes visible and separated.
Use mature restrained fantasy game art: very simple solid metal disks, slightly tilted elliptical front faces with a narrow visible thickness at lower right, clean smooth surfaces, broad soft diffuse lighting, understated semi-realistic proportions, not cartoon, not photographic texture. A single FLAT FOUR-POINT STAR symbol is centered on each face, not five points. NO bevel or faceted shading on stars. No inscriptions, scratches, patina, grain, speckles, decorative carving, bolts, sparkles, shine streaks or black outlines.
CRITICAL COLOR DESIGN: the three coins must be instantly distinguishable on a crowded match-3 board. LEFT COPPER is deep saturated reddish copper, subdued brick-red copper rather than orange or tan, average face approximately #99503B. MIDDLE SILVER is notably LIGHT cool pale blue-silver, average face approximately #C8D9E5, absolutely not warm gray, taupe or beige. RIGHT GOLD is clear rich yellow-gold, average face approximately #DEB52C, distinctly yellower than copper, not brown or orange. Copper darkest, gold medium-bright, silver lightest. Maintain strong hue and lightness separation across categories.
CRITICAL INTERNAL SIMPLICITY: each coin face is almost a flat color with a very broad gentle gradient. Star is only 12 percent darker than face, legible but quiet, not a strongly contrasting dark emblem. Single thin restrained rim only 8 percent lighter than face, NO white glints, NO multiple concentric rings, NO high-contrast dark inner ring. Keep rim and sidewall contrast subtle. At small size the viewer should perceive three distinct colored coin masses first, and star emblems second. No texture detail at all. Consistent light direction and finish. Render sharp clean usable sprite edges.`
  }
};
