import { expect, test } from '@playwright/test';
test('叶落 is visible in the collection with skill, traits and supplied portrait', async ({page})=>{
  await page.setViewportSize({width:1600,height:1100});
  await page.goto('/game.html#troop');
  await expect(page.locator('#collection')).toBeVisible({timeout:15000});
  await page.locator('[data-tab="all"]').click();
  await page.locator('#collectionSearch').fill('叶落');
  const card=page.locator('.collection-card');
  await expect(card).toHaveCount(1);
  await card.click();
  await expect(page.locator('#detail')).toContainText('猩红谢幕');
  await expect(page.locator('#detail')).toContainText('溅射');
  for(const name of ['血色生机','夜铸轻甲','赤月留痕']) await expect(page.locator('#traitList')).toContainText(name);
  await expect(page.locator('#lastTrait')).toContainText('配对红色宝石时');
  await expect(page.locator('#unlockCost')).toBeEmpty();
  await expect(page.locator('#unlockCost')).toBeHidden();
  const image=page.locator('#portraitArt');
  await expect(image).toHaveAttribute('src',/yeluo\.png/);
  await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true);
  await page.locator('#spellName').scrollIntoViewIfNeeded();
  await page.screenshot({path:'artifacts/yeluo-integration.png',fullPage:true});
});
