// sa-L76 B04 fill spec.
const T = 'tests/unit/gowLaneL7B04.test.ts';
const BRIAN = 'artifacts/gow-skill-audit/gold-primary-sources/official-brian-guide.html';
const R000 = { id: 'r000', role: 'user-ruling', path: 'tasks/active/gow-skill-shards/rulings/R000-waived-modes.md', note: 'R000: Tower / ascension-dependent clauses are waived (user-waived-mode); base steal and damage still verified.' };
const R001 = { id: 'r001', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R001-native-step-order.md', note: 'R001: native order governs; damage-then-TroopOrderFront vs pull-then-damage proven equivalent by test.' };
const NA = n => ['not-applicable', n];
const firstTwo = "Official Brian guide Cleave 'Deal [1+Magic] damage to the first 2 enemies' (same first-2 targeting wording); named-troop bonus clauses follow the stored English snapshot.";
const weaponDims = (o) => ({
  'identity-cost-colors': o.identity,
  'target-count-range': o.target,
  'base-formula-rounding': o.formula,
  'boost-source-ratio-cap': o.boost,
  'conditions-probabilities-branches': o.cond,
  'status-duration-immunity': NA('No status applied.'),
  'gems-types-selection-resolution': NA('No gem steps.'),
  'summon-transform-pools': NA('No summon/transform.'),
  'order-death-retargeting': o.order,
  'mana-economy-extra-turn': o.mana,
  'display-description': o.zh,
  'battle-pipeline': o.pipe,
});
module.exports = [
  {
    key: 'troop:7517',
    en: "troop 7517: stats.spell.id 9281, ManaCost 12, Blue/Yellow, English 'Pull an Enemy to the front, and deal [(Magic x 0.625) + 2] – [(Magic x 1.25) + 4] damage to them, boosted by my Armor. There is a 15% chance to self destruct. [2:1]' asserted verbatim.",
    native: 'spell 9281 Target Enemy Cost 12; SpellSteps asserted: CountArmor Self 50; RandomHighDamage FromTarget Amount 4 SPM 1.25 UseCounterForAmount Delay 400; TroopOrderFront FromTarget; LethalDamage Self PercentageChance 15.',
    rule: { path: BRIAN, note: "Official Brian guide writes stat boosts as '(Boost Ratio N:1)' (e.g. Frenzy 3:1, Resolve 4:1); supports the [2:1] self-armor boost label." },
    test: T, testNote: 'L7B04 troop:7517 describe: prototype (split removed) + zh; 4 real casts (2 sides x magic 0/8) with scripted low/high rolls; self destruct 0.1499 vs 0.15; R001 order equivalence + armor absorption; low-mana/silence; binding.',
    rulings: [R001],
    dims: {
      'identity-cost-colors': 'Entity 7517 -> spell 9281, cost 12, Blue/Yellow; ledger binding checks true.',
      'target-count-range': 'FromTarget -> enemyChosen only (after fix L7-7517 no split to the next enemy); pulled to front.',
      'base-formula-rounding': 'Roll in [0.625M+2 .. 1.25M+4] (magic 0: 2..4, magic 8: 7..14) plus floor(armor 21 / 2) = +10 on both ends; low roll 0 and high roll 0.9999 asserted.',
      'boost-source-ratio-cap': 'CountArmor Self Amount 50 = [2:1] -> selfStat armor ratio 2:1 (21 -> +10); no cap. Open note in issues L7-7517: whether native adds the counter to both range ends.',
      'conditions-probabilities-branches': 'LethalDamage Self PercentageChance 15 -> sacrifice allySelf chance 0.15: roll 0.1499 kills caster, 0.15 does not.',
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Native damage -> TroopOrderFront; runtime pull -> damage on the same chosen target: equivalent (same victim, final order [12,10,11,13]) per R001; self destruct after damage.',
      'mana-economy-extra-turn': 'Real cast spends 12 mana and ends the turn; low mana / silence block.',
      'display-description': "zh matches English clause by clause; official zh snapshot keeps a '- {2}' placeholder artefact after the range (kept verbatim, no behaviour).",
      'battle-pipeline': 'TurnEngine.castSkill both sides with scripted RNG; normal damage consumes target armor first.',
    },
    clauses: {
      c1: 'Chosen enemy pulled to front and alone takes the ranged roll + floor(my armor / 2); other enemies untouched.',
      c2: '15% self destruct: roll 0.1499 defeats the caster, 0.15 does not.',
      c3: '[2:1]: +1 per 2 own armor (21 -> +10).',
    },
    steps: {
      0: 'CountArmor Self 50 -> selfStat armor ratio 2:1.',
      1: 'RandomHighDamage FromTarget Amount 4 SPM 1.25 UseCounterForAmount -> damage enemyChosen rangeSpec {2+0.625M .. 4+1.25M} + modifier; exact low/high values asserted.',
      2: 'TroopOrderFront FromTarget -> reposition enemyChosen front (runtime before damage; order-equivalent, R001 test).',
      3: 'LethalDamage Self PercentageChance 15 -> sacrifice allySelf chance 0.15.',
    },
    branches: { main: 'Single branch with a 15% self destruct roll; both roll outcomes asserted.' },
  },
  {
    key: 'troop:6694',
    en: "troop 6694: stats.spell.id 8040, ManaCost 12, Red/Purple, English \"Steal a quarter of an Enemy's Armor, and deal [Magic + 4] damage to them. If they are a Tower, deal 3x - 5x damage, based on my Ascensions. [4:1]\" asserted verbatim.",
    native: 'spell 8040 Target Enemy Cost 12; SpellSteps asserted: CountArmor FromTarget 25; StealArmor FromTarget UseCounterForAmount; Damage FromTarget 4 SPM 1 StatusModifier MultiplyForAscensionCastle StatusAmount 3.',
    rule: { path: BRIAN, note: "Official Brian guide uses the same steal wording (Corruption 'Steal [0+Magic] Armor and 2 Attack from all enemies') and '(Boost Ratio 4:1)' notation (Resolve)." },
    test: T, testNote: 'L7B04 troop:6694 describe: binding/prototype/zh; 4 real casts (armor 40 -> steal 10, caster +10, then [Magic+4] into armor); rounding 7/3/0; only chosen enemy; low-mana/silence.',
    rulings: [R000],
    dims: {
      'identity-cost-colors': 'Entity 6694 -> spell 8040, cost 12, Red/Purple; ledger binding checks true.',
      'target-count-range': 'FromTarget -> enemyChosen for both steal and damage; other enemies keep armor 8/40.',
      'base-formula-rounding': 'Stolen = floor(armor x 25%) (40 -> 10, 7 -> 1, 3 -> 0); damage [Magic+4] normal, absorbed by remaining armor first.',
      'boost-source-ratio-cap': 'CountArmor FromTarget 25 = [4:1] quarter of target armor, credited to caster armor (gainStat armor); no cap.',
      'conditions-probabilities-branches': 'Only condition is the Tower x ascension multiplier, waived per R000 (c2).',
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Native order count -> steal -> damage kept: damage hits the post-steal armor (40 -> 30 -> 30-(M+4)).',
      'mana-economy-extra-turn': 'Real cast spends 12 mana and ends the turn; low mana / silence block.',
      'display-description': "zh '窃取敌人四分之一到护甲值，并对一名敌人造成 [魔法 + 4] 点伤害。如果敌人是个高塔，则基于我已晋升的稀有度造成 3 到 5 倍伤害。 [4:1]' matches English (the '到' is an official zh typo for '的').",
      'battle-pipeline': 'TurnEngine.castSkill both sides; caster armor 3 -> 13; target armor/Life exact.',
    },
    clauses: {
      c1: 'Quarter of the chosen enemy armor moves to the caster, then [Magic + 4] damage to the same enemy (through remaining armor).',
      c2: ['excluded', 'tower', "Waived per R000: 'If they are a Tower, deal 3x - 5x damage, based on my Ascensions' (Tower target + ascension scaling not implemented; existing Castle condMult placeholder untouched)."],
      c3: '[4:1]: 25% of target armor, floor (7 -> 1, 3 -> 0).',
    },
    steps: {
      0: 'CountArmor FromTarget 25 -> reduce fraction 0.25 of target armor.',
      1: 'StealArmor FromTarget UseCounterForAmount -> reduce enemyChosen armor + gainStat armor to caster.',
      2: 'Damage FromTarget 4 SPM 1 -> damage enemyChosen base 4 mult 1 (base asserted); its StatusModifier MultiplyForAscensionCastle part is the waived Tower clause c2 (R000).',
    },
    branches: { main: 'Single unconditional branch; covered by real casts.' },
  },
  {
    key: 'weapon:1476',
    en: "weapon 1476 Shadow-HuntersClaw: SpellId 8778, ManaCost 12, Green, English 'Deal [Magic + 1] damage to the first 2 Enemies. If Shadow-Hunter is on my team, gain 5 Attack.' asserted.",
    native: "spell 8778 Target None Cost 12; SpellSteps asserted: CountArmyTroop AllAllies 10000 Data '6106'; CountMax 5; Damage FirstTwoEnemies 1 SPM 1; IncreaseAttack Self UseCounterForAmount.",
    rule: { path: BRIAN, note: firstTwo },
    test: T, testNote: 'L7B04 weapon:1476 describe: binding (numeric + gw_), prototype, zh, troop 6106 name; 8 real casts; absent/dead/enemy-side/two Shadow-Hunters; dead front skipped; armor; low-mana/silence.',
    dims: weaponDims({
      identity: 'Weapon 1476 -> spell 8778, cost 12, Green, ReferenceName Shadow-HuntersClaw; numeric and gw_ prototypes identical.',
      target: 'FirstTwoEnemies -> enemyFirstN n 2: first two living enemies each take full damage; Self for Attack.',
      formula: '[Magic + 1] each (magic 0/10); +5 Attack flat.',
      boost: "CountArmyTroop Data '6106' x10000 capped by CountMax 5 -> 5 Attack when >=1 living Shadow-Hunter ally (troopPresent name 暗影猎手 = troop 6106); two present still 5.",
      cond: 'Condition Shadow-Hunter on my team: present -> +5; absent, defeated or on the enemy side -> +0.',
      order: 'Count precedes damage; Attack gain after damage; dead front enemy skipped (first two living).',
      mana: 'Real cast spends 12 mana and ends turn; low mana / silence block (no Attack gain).',
      zh: "zh '对首 2 名敌人造成 [魔法 + 1] 点伤害。若自身队伍中有暗影猎手，则获得 5 点攻击力。' matches English.",
      pipe: 'TurnEngine.castSkill both sides with numeric and gw_ skill ids.',
    }),
    clauses: {
      c1: 'First 2 living enemies take [Magic + 1] each; armor absorbs.',
      c2: 'Shadow-Hunter ally -> caster +5 Attack (ally itself unchanged); no bonus otherwise.',
    },
    steps: {
      0: "CountArmyTroop AllAllies Data '6106' Amount 10000 -> troopPresent ally 暗影猎手 (living).",
      1: 'CountMax 5 -> gain fixed at 5 (two Shadow-Hunters still +5).',
      2: 'Damage FirstTwoEnemies Amount 1 SPM 1 -> damage enemyFirstN n 2 base 1 mult 1.',
      3: 'IncreaseAttack Self UseCounterForAmount -> buff allySelf attack 5 gated by troopPresent.',
    },
    branches: { main: 'Single branch; the troop-present condition is covered on both outcomes.' },
  },
  {
    key: 'weapon:1473',
    en: "weapon 1473 RosesPistol: SpellId 8775, ManaCost 10, Yellow, English 'Deal [Magic + 1] true damage to an Enemy. If Bonnie Rose is on my team, gain 40 Gold.' asserted.",
    native: "spell 8775 Target Enemy Cost 10; SpellSteps asserted: CountArmyTroop AllAllies 10000 Data '6276'; CountMax 40; TrueDamage FromTarget 1 SPM 1; GiveGold Self UseCounterForAmount.",
    rule: { path: BRIAN, note: "Official Brian guide uses the same true damage wording (Curse of Weakness 'Deal [3+Magic] true damage', Blood Feast); the named-troop gold clause follows the English snapshot." },
    test: T, testNote: 'L7B04 weapon:1473 describe: binding (numeric + gw_), prototype, zh, troop 6276 name; 8 real casts (true damage through armor 50, +40 gold my side only); absent/dead/enemy Bonnie Rose; low-mana/silence.',
    dims: weaponDims({
      identity: 'Weapon 1473 -> spell 8775, cost 10, Yellow, ReferenceName RosesPistol; numeric and gw_ prototypes identical.',
      target: 'FromTarget -> enemyChosen only; gold to caster side.',
      formula: '[Magic + 1] true damage (armor 50 untouched); +40 gold flat.',
      boost: "CountArmyTroop Data '6276' x10000 capped by CountMax 40 -> 40 gold when Bonnie Rose (红玫瑰) is a living ally.",
      cond: 'Bonnie Rose present -> +40 gold; absent, defeated or enemy-side -> +0.',
      order: 'Count precedes damage; gold after damage.',
      mana: 'Real cast spends 10 mana and ends turn; low mana / silence block (no gold).',
      zh: "zh '对一名敌人造成 [魔法 + 1] 点真实伤害。若自身队伍中有红玫瑰，则获得 40 黄金。' matches English.",
      pipe: 'TurnEngine.castSkill both sides; goldForSide(caster side) +40, opponent gold unchanged.',
    }),
    clauses: {
      c1: '[Magic + 1] true damage to the chosen enemy, bypassing armor 50.',
      c2: 'Bonnie Rose ally -> +40 gold for my side only.',
    },
    steps: {
      0: "CountArmyTroop AllAllies Data '6276' Amount 10000 -> troopPresent ally 红玫瑰.",
      1: 'CountMax 40 -> gold fixed at 40.',
      2: 'TrueDamage FromTarget 1 SPM 1 -> damage enemyChosen trueDamage base 1 mult 1.',
      3: 'GiveGold Self UseCounterForAmount -> gainEconomy gold 40 gated by troopPresent.',
    },
    branches: { main: 'Single branch; troop-present condition covered on both outcomes.' },
  },
  {
    key: 'weapon:1721',
    en: "weapon 1721 GirthroksStonecleaver: SpellId 10065, ManaCost 20, Blue, English 'Deal [Magic + 4] damage to the first 2 Enemies. If Immortal Girthrok is in my team, give 12 Life to all Allies.' asserted.",
    native: "spell 10065 Target None Cost 20; SpellSteps asserted: CountArmyTroop AllAllies 10000 Data '7933'; Damage FirstTwoEnemies 4 SPM 1; CountMax 12; IncreaseHealth AllAllies UseCounterForAmount.",
    rule: { path: BRIAN, note: firstTwo + " IncreaseHealth ('give N Life') raises Life and max Life (engine LifeMode gain convention)." },
    test: T, testNote: 'L7B04 weapon:1721 describe: binding (numeric + gw_), prototype, zh, troop 7933 name; 8 real casts (first 2 damaged, every living ally +12 Life/+12 max Life); absent/dead/enemy Girthrok; dead ally not healed; low-mana/silence.',
    dims: weaponDims({
      identity: 'Weapon 1721 -> spell 10065, cost 20, Blue, ReferenceName GirthroksStonecleaver; numeric and gw_ prototypes identical.',
      target: 'FirstTwoEnemies -> enemyFirstN n 2; AllAllies -> allyAll living allies incl. caster.',
      formula: '[Magic + 4] to each of the first two; +12 Life and +12 max Life to each living ally.',
      boost: "CountArmyTroop Data '7933' x10000 capped by CountMax 12 -> 12 Life when Immortal Girthrok (不朽的格思洛克) is a living ally.",
      cond: 'Girthrok present -> Life for all allies; absent, defeated or enemy-side -> none.',
      order: 'Count first, damage, then CountMax/IncreaseHealth; dead ally not healed.',
      mana: 'Real cast spends 20 mana and ends turn; low mana / silence block.',
      zh: "zh '对首 2 位敌人造成 [魔法 + 4] 点伤害。若队伍中有不朽的格思洛克，为所有盟友提供 12 点生命值。' matches English.",
      pipe: 'TurnEngine.castSkill both sides; hp/maxHp pairs asserted ([912,1012],[512,1012],[1012,1012]); enemies max Life unchanged.',
    }),
    clauses: {
      c1: 'First two living enemies take [Magic + 4] each.',
      c2: 'Girthrok ally -> every living ally +12 Life (and +12 max Life); none otherwise.',
    },
    steps: {
      0: "CountArmyTroop AllAllies Data '7933' Amount 10000 -> troopPresent ally 不朽的格思洛克.",
      1: 'Damage FirstTwoEnemies 4 SPM 1 -> damage enemyFirstN n 2 base 4 mult 1.',
      2: 'CountMax 12 -> fixed 12.',
      3: 'IncreaseHealth AllAllies UseCounterForAmount -> buff allyAll hp 12 lifeMode gain gated by troopPresent.',
    },
    branches: { main: 'Single branch; troop-present condition covered on both outcomes.' },
  },
];
