// sa-L76 B05 fill spec (6352 stays draft: L7-6352-b source-dispute).
const T = 'tests/unit/gowLaneL7B05.test.ts';
const BRIAN = 'artifacts/gow-skill-audit/gold-primary-sources/official-brian-guide.html';
const WLIST = 'artifacts/gow-skill-audit/gold-primary-sources/official-weapon-list.html';
const R001 = { id: 'r001', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R001-native-step-order.md', note: 'R001: native SpellSteps order governs observable order (fixed L6-6549 / L6-7833 in round 2).' };
const R003 = { id: 'r003', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R003-count-threshold-labels.md', note: 'R003 item 2: Count* Amount is a percentage; [3:1] = 34% (armor 50 -> 17); implemented in round 2.' };
const NA = n => ['not-applicable', n];
module.exports = [
  {
    key: 'troop:7344',
    en: "troop 7344: stats.spell.id 8969, ManaCost 16, Yellow/Brown, English 'Deal [Magic + 2] damage to 4 random Enemies, boosted by my Armor. [3:1]' asserted verbatim.",
    native: 'spell 8969 Target None Cost 16; SpellSteps asserted: CountArmor Self 34; Damage RandomEnemy; 3 x Damage RandomPrefNotPrevEnemy (Amount 2 SPM 1 UseCounterForAmount, ResetTargets/Delay).',
    rule: { path: BRIAN, note: "Official Brian guide '(Boost Ratio 3:1)' notation (e.g. Frenzy); the separate-hit semantics follow the native RandomEnemy / RandomPrefNotPrevEnemy steps." },
    test: T, testNote: 'L7B05 troop:7344 describe: binding/prototype (4 segments)/zh; 4 real casts (4 hits, no consecutive repeat, armor 53 -> +18); 2 living alternate, 1 living x4, all enemies reachable over seeds; killed enemy not reselected; low-mana/silence.',
    rulings: [R003],
    dims: {
      'identity-cost-colors': 'Entity 7344 -> spell 8969, cost 16, Yellow/Brown; ledger binding checks true.',
      'target-count-range': 'Four separate single-target hits: RandomEnemy then 3 x RandomPrefNotPrevEnemy (prefer anyone but the previous victim, reuse if alone) -> 4 hits even with 1-2 living enemies.',
      'base-formula-rounding': 'Each hit [Magic+2] + floor(own armor x 34%): armor 53 -> +18 (R003), magic 0/10.',
      'boost-source-ratio-cap': 'CountArmor Self Amount 34 = [3:1] label -> selfStat armor, 34% floor; ally armor 60 ignored; no cap.',
      'conditions-probabilities-branches': 'Random selection only: seeds 1-12 reach all 4 enemies; consecutive hits never share a target while 2+ alive.',
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Counter first; an enemy killed by an earlier hit is never selected again (Life 2 case: exactly 1 hit on it).',
      'mana-economy-extra-turn': 'Real cast spends 16 mana and ends turn; low mana / silence block.',
      'display-description': "zh '对 4 名随机敌人造成 [魔法 + 2] 点伤害，伤害值因我的护甲值而增强。 [3:1]' matches English.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; 4 skill-damage events with exact damage.',
    },
    clauses: {
      c1: '4 random hits of [Magic + 2] boosted by my armor, as separate native steps (L7-7344 fixed).',
      c2: '[3:1] = 34% of own armor, floor (53 -> 18).',
    },
    steps: {
      0: 'CountArmor Self 34 -> selfStat armor ratio 3:1 evaluated as 34% (R003).',
      1: 'Damage RandomEnemy Amount 2 SPM 1 UseCounterForAmount -> damage enemyRandom.',
      2: 'Damage RandomPrefNotPrevEnemy -> damage enemyRandomPrefNotPrev (prefers other than previous).',
      3: 'Damage RandomPrefNotPrevEnemy -> damage enemyRandomPrefNotPrev.',
      4: 'Damage RandomPrefNotPrevEnemy -> damage enemyRandomPrefNotPrev.',
    },
    branches: { main: 'Single unconditional branch; covered by real casts.' },
  },
  {
    key: 'troop:6549',
    en: "troop 6549: stats.spell.id 7743, ManaCost 11, Yellow/Purple, English 'Deal [Magic + 2] true damage to an enemy. Steal 3 Armor and shift it to Magic. [1:1]' asserted verbatim.",
    native: 'spell 7743 Target Enemy Cost 11; SpellSteps asserted: CountArmor FromTarget 100; CountMax 3; DecreaseArmor FromTarget counter; IncreaseSpellPower Self counter; TrueDamage FromTarget 2 SPM 1.',
    rule: { path: BRIAN, note: "Official Brian guide uses the same true damage wording (Curse of Weakness 'Deal [3+Magic] true damage') and '(Boost Ratio N:1)' notation; armor-to-Magic shift follows the native DecreaseArmor + IncreaseSpellPower steps." },
    test: T, testNote: 'L7B05 troop:6549 describe: binding/prototype (reduce before trueDmg)/zh; 4 real casts (armor 5 -> 2, Magic +3, Life loss magic+5); armor 1 / 0 boundaries; true damage ignores armor, chosen only; low-mana/silence.',
    rulings: [R001],
    dims: {
      'identity-cost-colors': 'Entity 6549 -> spell 7743, cost 11, Yellow/Purple; ledger binding checks true.',
      'target-count-range': 'FromTarget -> enemyChosen for both armor reduction and true damage; others untouched.',
      'base-formula-rounding': 'Stolen = min(armor, 3); true damage = (Magic + stolen) + 2.',
      'boost-source-ratio-cap': 'CountArmor 100% capped by CountMax 3 -> reduce armor 3 gainStat magic 1:1; caster armor unchanged (DecreaseArmor, not StealArmor).',
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Native order kept (R001, L6-6549 fixed): Magic raised before TrueDamage, so damage uses the new Magic.',
      'mana-economy-extra-turn': 'Real cast spends 11 mana and ends turn; low mana / silence block (no Magic change).',
      'display-description': "zh '对一名敌人造成 [魔法 + 2] 点真实伤害。窃取 3 点护甲值并将之转换成魔力值。 [1:1]' matches English.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; true damage bypasses target armor (40 -> 37 only from the steal).',
    },
    clauses: {
      c1: '[Magic + 2] true damage to the chosen enemy, computed with the Magic after the shift.',
      c2: 'Target loses min(armor, 3) armor; caster gains the same Magic.',
      c3: '[1:1]: armor to Magic one for one.',
    },
    steps: {
      0: 'CountArmor FromTarget 100 -> counter = target armor.',
      1: 'CountMax 3 -> counter capped at 3 (reduce base 3 limited by actual armor).',
      2: 'DecreaseArmor FromTarget counter -> reduce enemyChosen armor.',
      3: 'IncreaseSpellPower Self counter -> gainStat magic of the reduced amount.',
      4: 'TrueDamage FromTarget 2 SPM 1 -> damage enemyChosen trueDamage base 2 mult 1 after the Magic gain.',
    },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'troop:7833',
    en: "troop 7833: stats.spell.id 10061, ManaCost 17, Blue/Green, English 'Deal [Magic + 4] damage to an Enemy, then pull them to the back. There is a 10% chance to slay them, boosted by their Armor (up to 30%). [10:1]' asserted verbatim.",
    native: 'spell 10061 Target Enemy Cost 17; SpellSteps asserted: CountArmor FromTarget 10; CountMax 20; LethalDamageConditional FromTarget Amount 10 counter; Damage FromTarget 4 SPM 1 Delay 400; TroopOrderBack FromTarget.',
    rule: { path: BRIAN, note: "Official Brian guide '(Boost Ratio N:1)' notation; here [10:1] = +1 percentage point of slay chance per 10 armor (native CountArmor 10 + CountMax 20)." },
    test: T, testNote: 'L7B05 troop:7833 describe: binding/prototype (execute first)/zh; 4 real casts failed roll (damage + pull back); pre-damage armor 100 -> 20% (0.19 vs 0.2001); 0 armor 10%; cap 30% at armor 400; armor 99 -> 19%; low-mana/silence.',
    rulings: [R001],
    dims: {
      'identity-cost-colors': 'Entity 7833 -> spell 10061, cost 17, Blue/Green; ledger binding checks true.',
      'target-count-range': 'All steps FromTarget -> enemyChosen (slay, damage, then pull to back).',
      'base-formula-rounding': '[Magic+4] damage; slay chance 10% + min(floor(armor x 10%), 20) points.',
      'boost-source-ratio-cap': 'CountArmor FromTarget 10 -> chosenStat armor ratio 10:1, CountMax 20 -> max 20 points (30% total cap).',
      'conditions-probabilities-branches': 'Slay roll: 0 armor 0.0999 slays / 0.1 not; armor 99 0.1899 / 0.19; armor 100 0.19 / 0.2001; armor 400 0.2999 / 0.3001.',
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Native order (R001, L6-7833 fixed): slay rolled on pre-damage armor; slain target is not damaged or moved (order [10,11,13]); survivor pulled to the back.',
      'mana-economy-extra-turn': 'Real cast spends 17 mana and ends turn; low mana / silence block.',
      'display-description': "zh '对敌人造成[魔法 + 4]点伤害，然后将其拉到后方。有10%的几率将其击杀，击杀几率受其护甲值提升（最高可达30%）。 [10:1]' matches English.",
      'battle-pipeline': 'TurnEngine.castSkill both sides with scripted rolls; reposition observed in team order.',
    },
    clauses: {
      c1: '[Magic + 4] to the chosen enemy, then it moves to the back (order [10,11,13,12]).',
      c2: '10% slay chance + 1 point per 10 pre-damage armor, capped at 30%.',
      c3: '[10:1] = +1% per 10 armor.',
    },
    steps: {
      0: 'CountArmor FromTarget 10 -> chosenStat armor, 10%.',
      1: 'CountMax 20 -> chanceBoost max 20.',
      2: 'LethalDamageConditional FromTarget Amount 10 counter -> execute enemyChosen chance 0.1 + boost, rolled first.',
      3: 'Damage FromTarget 4 SPM 1 -> damage enemyChosen base 4 mult 1 (skipped if slain).',
      4: 'TroopOrderBack FromTarget -> reposition lastTarget back (skipped if slain).',
    },
    branches: { main: 'Single branch with a slay roll; both outcomes asserted.' },
  },
  {
    key: 'weapon:1194',
    en: "weapon 1194 Fleshripper: SpellId 7752, ManaCost 15, Red/Yellow, English 'Eliminate all Armor from an Enemy. Deal [Magic + 4] damage, boosted by Armor eliminated. [3:1]' asserted.",
    native: 'spell 7752 Target Enemy Cost 15; SpellSteps asserted: CountArmor FromTarget 34; DecreaseArmor FromTarget 10001; Damage FromTarget 4 SPM 1 UseCounterForAmount.',
    rule: { path: WLIST, note: "Official weapon list Mang entry (same eliminate-armor family): 'Destroy an enemy's Armor. Deal [1+Magic] Damage. Increase my Attack by the amount of Armor destroyed. (Boost Ratio 1:1)'. Fleshripper itself is not in the stored list; its [3:1] label is evaluated as 34% per R003." },
    test: T, testNote: 'L7B05 weapon:1194 describe: raw + src binding, numeric/gw_ prototypes, zh; 8 real casts (armor 50 -> +17); R003 boundaries 2/3/30/53/0; low-mana/silence.',
    rulings: [R003],
    dims: {
      'identity-cost-colors': 'Weapon 1194 -> spell 7752, cost 15, Red/Yellow, ReferenceName Fleshripper; numeric and gw_ prototypes identical.',
      'target-count-range': 'FromTarget -> enemyChosen only; enemy 10 keeps armor 5.',
      'base-formula-rounding': '[Magic+4] + floor(eliminated armor x 34%) (R003): 50 -> 17, 53 -> 18, 30 -> 10, 3 -> 1, 2 -> 0.',
      'boost-source-ratio-cap': 'CountArmor FromTarget Amount 34 before elimination -> lastReduce (all armor removed) ratio 3:1 = 34%; no cap.',
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Count -> eliminate -> damage: damage hits Life directly after the armor is gone.',
      'mana-economy-extra-turn': 'Real cast spends 15 mana and ends turn; low mana / silence block.',
      'display-description': "zh '减除一名敌人全部护甲值，并造成 [魔法 + 4] 点伤害，数量因被减除的护甲值数而增强。 [3:1]' matches English.",
      'battle-pipeline': 'TurnEngine.castSkill both sides with numeric and gw_ skill ids.',
    },
    clauses: {
      c1: 'All armor of the chosen enemy removed (50 -> 0); caster gains none.',
      c2: '[Magic + 4] damage boosted by the armor eliminated.',
      c3: '[3:1] = 34% of the eliminated armor, floor (R003).',
    },
    steps: {
      0: 'CountArmor FromTarget 34 -> counter = 34% of target armor (lastReduce ratio 3:1 under R003).',
      1: 'DecreaseArmor FromTarget 10001 -> reduce enemyChosen armor drainAll.',
      2: 'Damage FromTarget 4 SPM 1 UseCounterForAmount -> damage enemyChosen base 4 mult 1 + counter.',
    },
    branches: { main: 'Single unconditional branch.' },
  },
];
