// sa-L76 B07 fill spec.
const T = 'tests/unit/gowLaneL7B07.test.ts';
const BRIAN = 'artifacts/gow-skill-audit/gold-primary-sources/official-brian-guide.html';
const R003 = { id: 'r003', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R003-count-threshold-labels.md', note: 'R003 item 2: [3:1] = native CountArmor 34%.' };
const NA = n => ['not-applicable', n];
const brianBoost = "Official Brian guide documents boosted spells with '(Boost Ratio N:1)' labels (e.g. Frenzy 3:1); [xN] multipliers follow the native Count Amount (N x 100).";
module.exports = [
  {
    key: 'troop:6595',
    en: "troop 6595: stats.spell.id 7817, ManaCost 12, Red/Brown, English 'Deal [Magic + 1] true damage to an enemy, boosted by their Armor. [3:1]' asserted verbatim.",
    native: 'spell 7817 Target Enemy Cost 12; SpellSteps asserted: CountArmor FromTarget 34; TrueDamage FromTarget 1 SPM 1 UseCounterForAmount.',
    rule: { path: BRIAN, note: "Official Brian guide true-damage wording (Curse of Weakness '[3+Magic] true damage ... (Boost Ratio 2:1)'); [3:1] evaluated as 34% per R003." },
    rulings: [R003], test: T,
    testNote: 'L7B07 troop:6595 describe: binding/prototype/zh; 4 real casts (target armor 50 -> +17, armor unchanged); R003 boundaries 0/2/3/53 with other armor ignored; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Entity 6595 -> spell 7817, cost 12, Red/Brown; ledger binding checks true.',
      'target-count-range': 'FromTarget -> enemyChosen only.',
      'base-formula-rounding': '[Magic+1] + floor(target armor x 34%) (R003): 50 -> 17, 53 -> 18, 3 -> 1, 2 -> 0.',
      'boost-source-ratio-cap': 'CountArmor FromTarget 34 -> targetStat armor of the same chosen target (its own segment target); caster/other enemy armor ignored; no cap.',
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Count before damage; true damage does not strip the counted armor.',
      'mana-economy-extra-turn': 'Real cast spends 12 mana and ends the turn; low mana / silence block.',
      'display-description': "zh '对一名敌人造成 [魔法 + 1] 点真实伤害，伤害值因其护甲值而增强。 [3:1]' asserted verbatim.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; exact Life loss, armor 50 kept.',
    },
    clauses: { c1: '[Magic + 1] true damage to the chosen enemy boosted by its own armor.', c2: '[3:1] = 34% floor (R003).' },
    steps: { 0: 'CountArmor FromTarget 34 -> targetStat armor ratio 3:1 (34%).', 1: 'TrueDamage FromTarget 1 SPM 1 counter -> damage enemyChosen trueDamage + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'weapon:1603',
    en: "weapon 1603 CaprichorsGlaive: SpellId 9383, ManaCost 20, Brown, English 'Deal [(Magic x 2) + 3] light splash damage to the Enemy. If Immortal Caprichor is in my team, Knock them to the back.' asserted.",
    native: "spell 9383 Target Enemy Cost 20; SpellSteps asserted: CountArmyTroop AllAllies 10000 Data '7576'; SplashDamage FromTarget 3 SPM 2 Delay 800; TroopOrderBackConditional FromTarget UseCounterForAmount.",
    rule: { path: 'artifacts/gow-skill-audit/gold-primary-sources/official-weapon-list.html', note: "Official weapon list adjacent-damage wording (Priest's Hammer 'Deal [2+Magic] damage to the first enemy, and 1 damage to any adjacent enemy'); light splash neighbour ratio 0.25 per the project's verified splash rule (operator guide section 3)." },
    test: T,
    testNote: 'L7B07 weapon:1603 describe: binding (numeric + gw_), prototype, troop 7576 name, zh; 8 real casts (chosen 2M+3, neighbours floor 25%, knocked to back with Caprichor); absent/dead/enemy Caprichor; front target one neighbour; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Weapon 1603 -> spell 9383, cost 20, Brown, ReferenceName CaprichorsGlaive; aliases identical.',
      'target-count-range': 'FromTarget -> enemyChosen with light splash to the adjacent living enemies (above/below).',
      'base-formula-rounding': 'Primary 2 x Magic + 3; neighbours floor(25%) (magic 10: 23 -> 5).',
      'boost-source-ratio-cap': NA('No count boost on damage; the troop counter only gates the knock back.'),
      'conditions-probabilities-branches': 'Immortal Caprichor (troop 7576) living ally -> knock the chosen enemy to the back; absent, dead or enemy-side -> no move.',
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Damage then conditional TroopOrderBack on the same primary target (order [10,12,13,11]).',
      'mana-economy-extra-turn': 'Real cast spends 20 mana and ends the turn; low mana / silence block (order unchanged).',
      'display-description': 'zh contains [(魔法 x 2) + 3] and the Caprichor troop name; matches English.',
      'battle-pipeline': 'TurnEngine.castSkill both sides with numeric and gw_ ids; team order observed.',
    },
    clauses: { c1: 'Light splash [(Magic x 2) + 3] on the chosen enemy, 25% to adjacent enemies.', c2: 'With Immortal Caprichor on my team the chosen enemy is knocked to the back.' },
    steps: { 0: "CountArmyTroop AllAllies Data '7576' -> troopPresent ally gate.", 1: 'SplashDamage FromTarget 3 SPM 2 -> damage enemyChosen range splash ratio 0.25.', 2: 'TroopOrderBackConditional FromTarget counter -> reposition lastTarget back ifCond troopPresent.' },
    branches: { main: 'Single branch; the troop-present condition covered on both outcomes.' },
  },
  {
    key: 'troop:7045',
    en: "troop 7045: stats.spell.id 8570, ManaCost 13, Green/Brown, English 'Give [Magic + 1] Attack and Life to the first Ally, boosted by Elementals, Elves, and Green Allies. [x2]' asserted verbatim.",
    native: "spell 8570 Target None Cost 13; SpellSteps asserted: CountArmyType AllAllies 200 'elemental'; CountArmyType AllAllies 200 'elf'; CountArmyColor AllAllies 200 '1' (Green); IncreaseAttack FrontAlly 1 SPM 1 counter; IncreaseHealth FrontAlly 1 SPM 1 counter.",
    rule: { path: BRIAN, note: brianBoost },
    test: T,
    testNote: 'L7B07 troop:7045 describe: binding/prototype (both segments boosted after L7-7045 fix)/zh; 4 real casts (count 4 -> +[Magic+1]+8 Attack and Life/max Life on the front ally only); non-Green caster, dead Elf, non-caster front ally; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Entity 7045 -> spell 8570, cost 13, Green/Brown; ledger binding checks true.',
      'target-count-range': 'FrontAlly -> allyFront (first living ally, not necessarily the caster); other allies untouched.',
      'base-formula-rounding': 'Attack and Life each = Magic + 1 + 2 x count; Life also raises max Life (IncreaseHealth).',
      'boost-source-ratio-cap': 'Three counts summed (Elemental, Elf, Green allies incl. caster; a troop matching two sources counts twice), x2 multiplier on both steps; dead allies excluded; no cap.',
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Counts precede both buffs; dead Elf not counted.',
      'mana-economy-extra-turn': 'Real cast spends 13 mana and ends the turn; low mana / silence block.',
      'display-description': "zh '给予第一位盟友 [魔法 + 1] 点攻击力和生命值，数值因元素、精灵和绿色盟友数而增强。 [x2]' asserted verbatim.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; exact attack/hp/maxHp.',
    },
    clauses: { c1: 'First ally gains [Magic + 1] Attack and Life, both boosted by Elementals, Elves and Green allies (fix L7-7045).', c2: '[x2]: +2 per counted troop on each stat.' },
    steps: { 0: "CountArmyType 'elemental' 200 -> alliesOfRace Elemental.", 1: "CountArmyType 'elf' 200 -> alliesOfRace Elf.", 2: "CountArmyColor '1' 200 -> alliesOfColor Green.", 3: 'IncreaseAttack FrontAlly counter -> buff allyFront attack + modifier.', 4: 'IncreaseHealth FrontAlly counter -> buff allyFront hp lifeMode gain + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'troop:6551',
    en: "troop 6551: stats.spell.id 7745, ManaCost 12, Green/Brown, English 'Deal [Magic + 3] damage to an enemy, boosted by allied Fey and Beasts. Gain 5 Souls. [x4]' asserted verbatim.",
    native: "spell 7745 Target Enemy Cost 12; SpellSteps asserted: CountArmyType AllAllies 400 'beast'; CountArmyType AllAllies 400 'fey' counter; Damage FromTarget 3 SPM 1 counter; GiveSouls Self 5.",
    rule: { path: BRIAN, note: brianBoost },
    test: T,
    testNote: 'L7B07 troop:6551 describe: binding/prototype/zh; 4 real casts (caster Fey+Beast counts 2, Beast ally 1 -> +12; +5 souls asserted on the Left side); no Fey/Beast, dead Beast, enemy Fey; armor; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Entity 6551 -> spell 7745, cost 12, Green/Brown; ledger binding checks true.',
      'target-count-range': 'FromTarget -> enemyChosen; souls to own side.',
      'base-formula-rounding': '[Magic+3] + 4 x (allied Fey + allied Beasts); a Fey-and-Beast troop counts in both.',
      'boost-source-ratio-cap': 'CountArmyType beast + fey AllAllies Amount 400 -> multiplier 4 over alliesOfRace Fey + Beast (caster included); enemies and dead allies excluded; no cap.',
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Counts precede damage; souls after damage.',
      'mana-economy-extra-turn': 'Real cast spends 12 mana and ends the turn; GiveSouls Self 5 -> economy souls +5 (asserted for the Left/player side).',
      'display-description': "zh '对一名敌人造成 [魔法 + 3] 点伤害，伤害值因已方的妖仙和野兽盟友数而增强。获得 5 个灵魂。 [x4]' asserted verbatim ('已方' is a zh typo for '己方'; meaning matches English).",
      'battle-pipeline': 'TurnEngine.castSkill both sides; armor absorbs normal damage.',
    },
    clauses: { c1: '[Magic + 3] to the chosen enemy boosted by allied Fey and Beasts.', c2: 'Gain 5 Souls.', c3: '[x4] per counted troop.' },
    steps: { 0: "CountArmyType 'beast' 400 -> alliesOfRace Beast.", 1: "CountArmyType 'fey' 400 counter -> alliesOfRace Fey summed.", 2: 'Damage FromTarget 3 SPM 1 counter -> damage enemyChosen + modifier.', 3: 'GiveSouls Self 5 -> gainEconomy souls 5.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'troop:6271',
    en: "troop 6271: stats.spell.id 7417, ManaCost 11, Blue/Yellow, English 'All allied Rogues gain [Magic + 1] Attack. Give 10 Gold, boosted by allied Rogues. [x5]' asserted verbatim.",
    native: "spell 7417 Target None Cost 11; SpellSteps asserted: CountArmyType AllAllies 500 'rogue'; IncreaseAttack AllyType 'rogue' 1 SPM 1; GiveGold 10 counter.",
    rule: { path: BRIAN, note: brianBoost },
    test: T,
    testNote: 'L7B07 troop:6271 describe: binding/prototype/zh; 4 real casts (living Rogue allies incl. caster +[Magic+1] Attack, non-Rogue/enemy Rogue unchanged, gold 10+5x2 own side only); no Rogue, dead Rogue; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Entity 6271 -> spell 7417, cost 11, Blue/Yellow; ledger binding checks true.',
      'target-count-range': 'AllyType rogue -> allyAll filtered targetRace Rogue (living only); gold to casting side.',
      'base-formula-rounding': 'Attack +[Magic+1] per Rogue ally; gold 10 + 5 x living Rogue allies.',
      'boost-source-ratio-cap': "CountArmyType 'rogue' AllAllies 500 -> multiplier 5 over alliesOfRace Rogue (caster included); dead Rogue and enemy Rogue excluded; no cap.",
      'conditions-probabilities-branches': NA('No condition/chance.'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Count first; buff and gold after; dead Rogue neither buffed nor counted.',
      'mana-economy-extra-turn': 'Real cast spends 11 mana and ends the turn; gold credited to casting side only; low mana / silence block.',
      'display-description': "zh '所有盟友盗贼获得 [魔法 + 1] 点攻击力。给予 10 黄金，黄金数量因盟友盗贼数而增强。 [x5]' asserted verbatim.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; goldForSide exact.',
    },
    clauses: { c1: 'Every living allied Rogue gains [Magic + 1] Attack.', c2: 'Gain 10 Gold + 5 per allied Rogue.', c3: '[x5] per Rogue.' },
    steps: { 0: "CountArmyType 'rogue' 500 -> alliesOfRace Rogue x5.", 1: "IncreaseAttack AllyType 'rogue' 1 SPM 1 -> buff allyAll attack targetRace Rogue.", 2: 'GiveGold 10 counter -> gainEconomy gold 10 + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
];
