// sa-L76 B06 fill spec: R003 re-review of the "Eliminate all Armor" [3:1] weapons + troop:6320.
const T = 'tests/unit/gowLaneL7B06.test.ts';
const BRIAN = 'artifacts/gow-skill-audit/gold-primary-sources/official-brian-guide.html';
const WLIST = 'artifacts/gow-skill-audit/gold-primary-sources/official-weapon-list.html';
const R003 = { id: 'r003', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R003-count-threshold-labels.md', note: 'R003 item 2: Count* Amount is a percentage; [3:1] = native 34% (armor 50 -> 17); implemented in round 2 (secondary.ts modifierBonus).' };
const NA = n => ['not-applicable', n];
const mangRule = { path: WLIST, note: "Official weapon list Mang entry (same eliminate-armor family): 'Destroy an enemy's Armor ... Increase my Attack by the amount of Armor destroyed. (Boost Ratio 1:1)'. This weapon is not in the stored list; its [3:1] label is evaluated as 34% per R003." };
const common = (o) => ({
  'identity-cost-colors': o.id,
  'target-count-range': o.target,
  'base-formula-rounding': o.formula,
  'boost-source-ratio-cap': 'CountArmor FromTarget Amount 34 before DecreaseArmor 10001 -> lastReduce ratio 3:1 evaluated as floor(eliminated x 34%) (R003): 0 -> 0, 2 -> 0, 3 -> 1, 50 -> 17, 53 -> 18; no cap.',
  'conditions-probabilities-branches': NA('No condition/chance.'),
  'status-duration-immunity': o.status ?? NA('No status applied.'),
  'gems-types-selection-resolution': NA('No gem steps.'),
  'summon-transform-pools': NA('No summon/transform.'),
  'order-death-retargeting': o.order,
  'mana-economy-extra-turn': o.mana,
  'display-description': o.zh,
  'battle-pipeline': 'TurnEngine.castSkill both sides with numeric and gw_ skill ids; blocked by low mana / silence (armor 30 kept).',
});
const elim = { c1: 'All armor of the chosen enemy removed (50 -> 0); other enemy keeps armor 4.' };
module.exports = [
  {
    key: 'weapon:1199',
    en: "weapon 1199 EarthsFury: SpellId 7757, ManaCost 15, Red/Brown, English 'Eliminate all Armor from an Enemy, and deal [Magic + 5] damage. Give all Allies 2 Attack, boosted by Armor eliminated. [3:1]' asserted.",
    native: 'spell 7757 Target Enemy Cost 15; SpellSteps asserted: CountArmor FromTarget 34; DecreaseArmor FromTarget 10001; Damage FromTarget 5 SPM 1; IncreaseAttack AllAllies Amount 2 UseCounterForAmount.',
    rule: mangRule, rulings: [R003], test: T,
    testNote: 'L7B06 weapon:1199 describe: binding (numeric + gw_) + zh verbatim; 8 real casts (armor 50 -> living allies +19 Attack, dead ally unchanged); R003 boundaries 0/2/3/53; low-mana/silence.',
    dims: common({
      id: 'Weapon 1199 -> spell 7757, cost 15, Red/Brown, ReferenceName EarthsFury; numeric and gw_ prototypes identical.',
      target: 'FromTarget -> enemyChosen for elimination and damage; AllAllies -> every living ally incl. caster for Attack.',
      formula: '[Magic+5] to Life after armor removal; Attack +2 + floor(eliminated x 34%).',
      order: 'Count -> eliminate -> damage -> Attack; dead ally not buffed.',
      mana: 'Real cast spends 15 mana and ends the turn.',
      zh: "zh '减除一名敌人全部护甲值，并造成 [魔法 + 5] 点伤害。给予所有盟友 2 点攻击力，数量因被减除的护甲值数而增强。 [3:1]' asserted verbatim.",
    }),
    clauses: { c1: 'All armor of the chosen enemy removed, then [Magic + 5] damage to it.', c2: 'Every living ally gains 2 Attack + 34% of the armor eliminated.', c3: '[3:1] = 34% floor (R003).' },
    steps: { 0: 'CountArmor FromTarget 34 -> lastReduce ratio 3:1 (34%).', 1: 'DecreaseArmor FromTarget 10001 -> reduce drainAll.', 2: 'Damage FromTarget 5 SPM 1 -> damage enemyChosen base 5 mult 1.', 3: 'IncreaseAttack AllAllies 2 counter -> buff allyAll attack base 2 + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'weapon:1201',
    en: "weapon 1201 TrickstersShot: SpellId 7759, ManaCost 15, Green/Purple, English 'Eliminate all Armor from an Enemy, and deal [Magic + 3] damage. Gain 2 Magic, boosted by Armor eliminated. [3:1]' asserted.",
    native: 'spell 7759 Target Enemy Cost 15; SpellSteps asserted: CountArmor FromTarget 34; DecreaseArmor 10001; Damage FromTarget 3 SPM 1; IncreaseSpellPower Self Amount 2 UseCounterForAmount.',
    rule: mangRule, rulings: [R003], test: T,
    testNote: 'L7B06 weapon:1201 describe: binding + zh verbatim; 8 real casts (damage with pre-gain Magic, self +19 Magic, ally unchanged); R003 boundaries; Web blocks gain; low-mana/silence.',
    dims: common({
      id: 'Weapon 1201 -> spell 7759, cost 15, Green/Purple, ReferenceName TrickstersShot; aliases identical.',
      target: 'FromTarget -> enemyChosen; Self -> caster only for Magic.',
      formula: '[Magic+3] with the pre-gain Magic; Magic +2 + floor(eliminated x 34%).',
      status: 'Web on the caster blocks the Magic gain (engine webbed rule); armor still eliminated.',
      order: 'Damage (step 2) precedes IncreaseSpellPower (step 3): damage uses the old Magic.',
      mana: 'Real cast spends 15 mana and ends the turn.',
      zh: "zh '减除一名敌人全部护甲值，并造成 [魔法 + 3] 点伤害。获得 2 点魔力值，数量因被减除的护甲值数而增强。 [3:1]' asserted verbatim.",
    }),
    clauses: { c1: 'Chosen enemy armor removed, then [Magic + 3] damage.', c2: 'Caster gains 2 Magic + 34% of the armor eliminated.', c3: '[3:1] = 34% floor (R003).' },
    steps: { 0: 'CountArmor FromTarget 34 -> lastReduce 34%.', 1: 'DecreaseArmor 10001 -> drainAll.', 2: 'Damage FromTarget 3 SPM 1 -> damage enemyChosen.', 3: 'IncreaseSpellPower Self 2 counter -> buff allySelf magic.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'weapon:1204',
    en: "weapon 1204 GoldenSun: SpellId 7799, ManaCost 13, Yellow/Purple, English 'Eliminate all Armor from an Enemy. Gain [Magic + 1] Gold, boosted by Armor eliminated. [3:1]' asserted.",
    native: 'spell 7799 Target Enemy Cost 13; SpellSteps asserted: CountArmor FromTarget 34; DecreaseArmor 10001; GiveGold Self Amount 1 SPM 1 UseCounterForAmount.',
    rule: mangRule, rulings: [R003], test: T,
    testNote: 'L7B06 weapon:1204 describe: binding + zh verbatim; 8 real casts (no damage, own gold + magic+1+17, opponent gold unchanged); R003 boundaries; low-mana/silence.',
    dims: common({
      id: 'Weapon 1204 -> spell 7799, cost 13, Yellow/Purple, ReferenceName GoldenSun; aliases identical.',
      target: 'FromTarget -> enemyChosen armor only (no damage); gold to caster side.',
      formula: 'Gold = Magic + 1 + floor(eliminated x 34%).',
      order: 'Count -> eliminate -> gold.',
      mana: 'Real cast spends 13 mana and ends the turn; gold credited to casting side only.',
      zh: "zh '减除一名敌人全部护甲值。获得 [魔法 + 1] 黄金，数量因被减除的护甲值而增强。 [3:1]' asserted verbatim.",
    }),
    clauses: { c1: 'Chosen enemy armor removed; no damage.', c2: 'Own side gains [Magic + 1] + 34% of armor eliminated gold.', c3: '[3:1] = 34% floor (R003).' },
    steps: { 0: 'CountArmor FromTarget 34 -> lastReduce 34%.', 1: 'DecreaseArmor 10001 -> drainAll.', 2: 'GiveGold Self 1 SPM 1 counter -> gainEconomy gold base 1 mult 1 + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'weapon:1200',
    en: "weapon 1200 YasminesPride: SpellId 7758, ManaCost 15, Green/Brown, English 'Eliminate all Armor from an Enemy. Give all Allies [Magic + 1] Life, boosted by Armor eliminated. [3:1]' asserted.",
    native: 'spell 7758 Target Enemy Cost 15; SpellSteps asserted: CountArmor FromTarget 34; DecreaseArmor 10001; IncreaseHealth AllAllies Amount 1 SPM 1 UseCounterForAmount.',
    rule: mangRule, rulings: [R003], test: T,
    testNote: 'L7B06 weapon:1200 describe: binding + zh verbatim; 8 real casts (each living ally +Life and +max Life = magic+18, dead ally unchanged, no damage); R003 boundaries; low-mana/silence.',
    dims: common({
      id: 'Weapon 1200 -> spell 7758, cost 15, Green/Brown, ReferenceName YasminesPride; aliases identical.',
      target: 'FromTarget -> enemyChosen armor only; AllAllies living allies incl. caster for Life.',
      formula: 'Life gain = Magic + 1 + floor(eliminated x 34%), also raising max Life (IncreaseHealth).',
      order: 'Count -> eliminate -> Life; dead ally not revived/buffed.',
      mana: 'Real cast spends 15 mana and ends the turn.',
      zh: "zh '减除一名敌人全部护甲值。给予所有盟友 [魔法 + 1] 点生命值，数量因被减除的护甲值数而增强。 [3:1]' asserted verbatim.",
    }),
    clauses: { c1: 'Chosen enemy armor removed; no damage.', c2: 'Every living ally gains [Magic + 1] + 34% of armor eliminated Life and max Life.', c3: '[3:1] = 34% floor (R003).' },
    steps: { 0: 'CountArmor FromTarget 34 -> lastReduce 34%.', 1: 'DecreaseArmor 10001 -> drainAll.', 2: 'IncreaseHealth AllAllies 1 SPM 1 counter -> buff allyAll hp lifeMode gain.' },
    branches: { main: 'Single unconditional branch.' },
  },
  {
    key: 'troop:6320',
    en: "troop 6320: stats.spell.id 7470, ManaCost 15, Blue/Red, English 'Deal 8 true scatter damage, boosted by all Ally and Enemy Armor. [3:1]' asserted verbatim.",
    native: 'spell 7470 Cost 15; SpellSteps asserted: CountArmor AllEnemies 34; CountArmor AllAllies 34 UseCounterForAmount; TrueScatterDamage AllEnemies Amount 8 UseCounterForAmount.',
    rule: { path: BRIAN, note: "Official Brian guide '(Boost Ratio 3:1)' label (e.g. Frenzy); the label is evaluated as the native 34% per R003. No stored official page describes scatter allocation (pool total asserted)." },
    rulings: [R003], test: T,
    testNote: 'L7B06 troop:6320 describe: binding/prototype/zh; 4 real casts (50 total armor -> pool 8 + 17 = 25, true, magic-independent); R003 boundaries 0/2/3/12/53; dead troops excluded; low-mana/silence.',
    dims: {
      'identity-cost-colors': 'Entity 6320 -> spell 7470, cost 15, Blue/Red; ledger binding checks true.',
      'target-count-range': 'AllEnemies -> enemyAll range scatter over living enemies; dead enemy receives nothing.',
      'base-formula-rounding': 'Pool = 8 + floor((ally armor + enemy armor) x 34%) (R003): 50 -> 25 (floor(50/3) would give 24); magic-independent.',
      'boost-source-ratio-cap': 'Two CountArmor steps Amount 34 summed into one counter -> sources allyStatSum + enemyStatSum armor, ratio 3:1 = 34%: 2 -> 0, 3 -> 1, 12 -> 4, 53 -> 18; dead troops excluded; no cap.',
      'conditions-probabilities-branches': NA('No condition/chance; allocation randomness only affects the split (total asserted).'),
      'status-duration-immunity': NA('No status applied.'),
      'gems-types-selection-resolution': NA('No gem steps.'),
      'summon-transform-pools': NA('No summon/transform.'),
      'order-death-retargeting': 'Counts precede the scatter; dead troops not counted and not hit.',
      'mana-economy-extra-turn': 'Real cast spends 15 mana and ends the turn; low mana / silence block.',
      'display-description': "zh '造成 8 点真实散射伤害，伤害值因敌我双方的护甲值而增强。 [3:1]' asserted verbatim.",
      'battle-pipeline': 'TurnEngine.castSkill both sides; true damage leaves enemy armor unchanged; events carry range scatter.',
    },
    clauses: { c1: '8 true scatter damage boosted by all ally and enemy armor: pool total exact both sides.', c2: '[3:1] = 34% of the summed armor, floor (R003).' },
    steps: { 0: 'CountArmor AllEnemies 34 -> enemyStatSum armor.', 1: 'CountArmor AllAllies 34 UseCounterForAmount -> allyStatSum armor added to the same counter.', 2: 'TrueScatterDamage AllEnemies 8 counter -> damage enemyAll scatter trueDamage base 8 + modifier.' },
    branches: { main: 'Single unconditional branch.' },
  },
];
