// Lane L5 round-3 re-judge spec builder (lane-owned helper, not evidence).
//   node tasks/active/gow-skill-shards/lane-L5/spec-r3.mjs  -> writes lane-L5/spec-r3-bNN.json
import fs from 'node:fs';
const dir = 'tasks/active/gow-skill-shards/lane-L5';
const R3 = 'tests/unit/gowLaneL5R3.test.ts';
const extraBase = [
  { id: 'r004', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R004-status-durations.md', note: 'R004: negatives no turn cap, shared cumulative self-cleanse 10%/+10% (+5% Cursed), Poison never; positives end on trigger (Barrier/Reflect damage, Enchanted cast, Enraged skull damage, Submerged/Blessed holder action).' },
  { id: 'r3', role: 'lane-battle-test', path: R3, note: 'Round-3 real castSkill both sides: statuses from this cast unchanged after 6 failed turn-start rolls; one successful roll removes all recoverable negatives together (Poison/positives stay).' },
  { id: 'srcR004', role: 'community-source', path: 'artifacts/gow-skill-audit/gold-primary-sources/community-2026-09-28-status-durations.json', note: 'Saved community corroboration for R004 (staff reply: new negative resets, all negatives cleanse together).' },
];
const r006 = { id: 'r006', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R006-hidden-mechanics-conventions.md', note: 'R006 conventions C1 (half-up rounding) / C2 (Cause* Amount ignored).' };
const r001 = { id: 'r001', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R001-native-step-order.md', note: 'R001: native SpellSteps order governs observable order.' };
const r002 = { id: 'r002', role: 'coordinator-ruling', path: 'tasks/active/gow-skill-shards/rulings/R002-barrier-enchant-cleanse.md', note: 'R002: Barrier/Enchanted no time limit; Cleanse removes negatives only.' };
const rule = { path: 'artifacts/gow-skill-audit/gold-primary-sources/official-status-effects.html' };
const NA = n => ['na', n];
const V = n => ['v', n];
const common = (o) => ({
  'identity-cost-colors': V(o.id),
  'target-count-range': V(o.target),
  'base-formula-rounding': o.formula ? V(o.formula) : NA('No numeric formula.'),
  'boost-source-ratio-cap': o.boost ? V(o.boost) : NA('No boost/count source.'),
  'conditions-probabilities-branches': o.cond ? V(o.cond) : NA('No condition, chance or Randomize.'),
  'status-duration-immunity': V(o.status),
  'gems-types-selection-resolution': NA('No gem steps.'),
  'summon-transform-pools': NA('No summon/transform.'),
  'order-death-retargeting': V(o.order),
  'mana-economy-extra-turn': V(o.mana ?? 'Cast spends full mana and passes the turn; low mana and Silence block the real cast (no mana/action spent).'),
  'display-description': V(o.zh ?? 'Chinese description asserted verbatim; wording matches the English effect.'),
  'battle-pipeline': V('Real TurnEngine.castSkill both sides (lane file + round-3 R004 file).'),
});
const DUR = 'R004: no turn cap; persists through 6 failed turn-start rolls, removed by one successful shared self-cleanse roll (gowLaneL5R3).';
const specs = {
  b01: {
    'weapon:1368': { test: 'tests/unit/gowLaneL5B01.test.ts', extra: [...extraBase, r002],
      en: 'weapon 1368 Lockstone: gowhead English "Gain a Barrier. Deal [Magic + 3] damage to an Enemy, and Silence them.", cost 13 Green, numeric 8403 + gw_Lockstone aliases.',
      native: 'spell 8403 Target Enemy: CauseBarrier Self Amount 1; Damage FromTarget Amount 3 SPM 1; CauseSilence FromTarget.',
      dims: common({ id: 'Weapon 1368 -> spell 8403, cost 13, Green; both aliases resolve to the same prototype.', target: 'Self Barrier (caster only, allies untouched); chosen enemy 12 takes damage and Silence; other enemies untouched.', formula: 'Magic+3: magic 0 -> 3, magic 9 -> 12 (armor first).', status: 'Barrier no time limit (R002); Silence ' + DUR + ' Invulnerable immune; re-apply refreshes (single instance, resets chance).', order: 'Events barrier -> dmg -> silence = native order; enemy Barrier absorbs damage but Silence lands; lethal hit leaves no Silence.' }),
      clauses: { c1: V('Caster gains Barrier (no time limit, R002).'), c2: V('Chosen enemy takes Magic+3 then is Silenced; Silence per R004.') },
      steps: { 0: V('CauseBarrier Self -> status barrier allySelf; Amount ignored (R006-C2).'), 1: V('Damage FromTarget 3/1 -> enemyChosen base 3 mult 1.'), 2: V('CauseSilence FromTarget -> lastTarget silence; duration R004.') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6406': { test: 'tests/unit/gowLaneL5B01.test.ts', extra: [...extraBase, r001, r002],
      en: 'troop 6406 Waverider: spell 7561 "Give an ally [Magic + 3] Armor and Barrier, then Submerge them.", cost 10 Blue/Yellow.',
      native: 'spell 7561 Target Ally: CauseBarrier FromTarget; IncreaseArmor FromTarget Amount 3 SPM 1; CauseSubmerged FromTarget.',
      dims: common({ id: 'Troop 6406 -> spell 7561, cost 10, Blue/Yellow.', target: 'Only the chosen ally (caster may choose itself); dead ally not a legal target (cast refused).', formula: 'Armor +Magic+3: magic 0 -> 3, magic 11 -> 14.', status: 'Barrier no time limit (R002); Submerged no timer and no natural cleanse, ends when the holder casts (real castSkill in gowLaneL5R3) (R004); Blessed ally blocks Barrier/Submerge but keeps Armor.', order: 'Prototype Armor->Barrier->Submerge vs native Barrier->Armor->Submerge: unobservable (Armor gain unaffected by Barrier; Blessed case shows the same result), per R001 equivalence case in B01.' }),
      clauses: { c1: V('Chosen ally gains Magic+3 Armor, Barrier, then Submerged (R004: ends on holder action).') },
      steps: { 0: V('CauseBarrier FromTarget -> barrier allyChosen.'), 1: V('IncreaseArmor 3/1 -> buff armor allyChosen.'), 2: V('CauseSubmerged -> submerged allyChosen; R004 duration.') },
      branches: { main: V('Single unconditional branch.') } },
    'weapon:1369': { test: 'tests/unit/gowLaneL5B01.test.ts', extra: [...extraBase, r002, r006],
      en: 'weapon 1369 Keystone: gowhead English "Gain a Barrier. Give [(Magic x 1.5) + 1] Life to an Ally. Then Cleanse and Enchant them.", cost 13 Red, 8404 + gw_Keystone aliases.',
      native: 'spell 8404 Target Ally: CauseBarrier Self Amount 1; IncreaseHealth FromTarget Amount 1 SPM 1.5; Cleanse FromTarget; CauseEnchanted FromTarget.',
      dims: common({ id: 'Weapon 1369 -> spell 8404, cost 13, Red; both aliases.', target: 'Self Barrier; chosen ally (self allowed) gains Life, Cleanse, Enchant; dead ally refused.', formula: 'Life 1.5*Magic+1 rounded half-up: magic 7 -> 12, magic 9 -> 15, magic 0 -> 1. convention:R006-C1', status: 'Cleanse removes negatives only, keeps Barrier (R002); Enchanted until cast (R002/R004).', order: 'Native order Barrier -> Life -> Cleanse -> Enchant; self-target keeps the Barrier gained in step 0.' }),
      clauses: { c1: V('Caster Barrier.'), c2: V('Ally gains round(1.5M)+1 Life. convention:R006-C1'), c3: V('Cleanse (negatives only) then Enchanted.') },
      steps: { 0: V('CauseBarrier Self.'), 1: V('IncreaseHealth SPM 1.5 base 1 -> buff hp lifeMode gain; half-up rounding convention:R006-C1.'), 2: V('Cleanse FromTarget -> cleanse lastTarget (R002).'), 3: V('CauseEnchanted -> enchanted lastTarget.') },
      branches: { main: V('Single unconditional branch.') } },
  },
  b02: {
    'weapon:1142': { test: 'tests/unit/gowLaneL5B02.test.ts', extra: [...extraBase, r006],
      en: 'weapon 1142 Dragonator 8000: gowhead English "Scientifically Burn, Freeze, Silence, and deal [Magic + 3] damage to random Enemies.", cost 11 Brown, 7338 + gw_Dragonator8000.',
      native: 'spell 7338 Target None: CauseBurning RandomEnemy Amount 2; CauseFrozen RandomPrefNotPrevEnemy Amount 2; CauseSilence RandomPrefNotPrevEnemy Amount 2; Damage RandomPrefNotPrevEnemy Amount 3 SPM 1.',
      dims: common({ id: 'Weapon 1142 -> spell 7338, cost 11, Brown; both aliases.', target: 'Step 1 random enemy; steps 2-4 each avoid the previous target while another enemy lives (40 seeds); lone survivor gets all.', formula: 'Magic+3 damage to one random enemy.', cond: 'Random picks via seeded RNG; prefer-not-previous verified over 40 seeds.', status: 'Burning/Frozen/Silence ' + DUR + ' Cause* Amount 2 ignored convention:R006-C2; Invulnerable immune.', order: 'Burn -> Freeze -> Silence -> Damage native order.' }),
      clauses: { c1: V('Burn, Freeze, Silence and Magic+3 damage on random enemies with prefer-not-previous; durations R004, Amount 2 ignored convention:R006-C2.') },
      steps: { 0: V('CauseBurning RandomEnemy -> enemyRandom burning; Amount ignored convention:R006-C2.'), 1: V('CauseFrozen RandomPrefNotPrevEnemy -> enemyRandomPrefNotPrev; convention:R006-C2.'), 2: V('CauseSilence RandomPrefNotPrevEnemy; convention:R006-C2.'), 3: V('Damage RandomPrefNotPrevEnemy 3/1.') },
      branches: { main: V('Single unconditional branch.') } },
    'weapon:1436': { test: 'tests/unit/gowLaneL5B02.test.ts', extra: [...extraBase, r001, r002],
      en: 'weapon 1436 Trick and Treat: gowhead English "Inflict all negative status effects on an Enemy, and grant myself all positive status effects.", cost 22 Red/Yellow/Purple, 8668 + gw_TrickAndTreat.',
      native: 'spell 8668 Target Enemy: CauseCursed FromTarget Amount 1; CauseAllNegativeStatusEffects FromTarget Delay 1; CauseAllPositiveStatusEffects Self.',
      dims: common({ id: 'Weapon 1436 -> spell 8668, cost 22, Red/Yellow/Purple; both aliases.', target: 'Negatives on the chosen enemy only; positives on the caster only.', status: 'Official negative list (15 incl. Faerie Fire/Hunter\'s Mark/Terror/Lycanthropy, no Charm); six positives, Enrage once; ' + DUR + ' Poison stays; positives persist. Curse strips Barrier and penetrates immunity; Invulnerable blocks; Blessed enemy cancels with Curse.', order: 'Curse first (native), then remaining negatives, then self positives with Blessed last.' }),
      clauses: { c1: V('All official negatives on the enemy, all positives on self; durations R004.') },
      steps: { 0: V('CauseCursed FromTarget -> curse enemyChosen first.'), 1: V('CauseAllNegativeStatusEffects -> 14 further negative segments on enemyChosen.'), 2: V('CauseAllPositiveStatusEffects Self -> randomStatus allPositive (Enrage once, Blessed last).') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6249': { test: 'tests/unit/gowLaneL5B02.test.ts', extra: [...extraBase],
      en: 'troop 6249 Penitent: spell 7392 "Death Mark the first and last Enemies. Take 3 damage.", cost 7 Blue.',
      native: 'spell 7392 Target None: CauseDeathMark FrontEnemy Amount 1; CauseDeathMark LastEnemy; Damage Self Amount 3.',
      dims: common({ id: 'Troop 6249 -> spell 7392, cost 7, Blue.', target: 'First and last living enemies; single survivor marked once; dead edges skip to living edge.', formula: 'Self damage fixed 3, magic-independent (magic 0/10).', status: 'Death Mark ' + DUR + ' death roll unchanged (graceTicks); Warded immune.', order: 'Mark front -> mark last -> self damage; self damage absorbed by caster Barrier, else Armor then Life; 3 Life defeats caster.' }),
      clauses: { c1: V('Front and last enemies Death Marked; R004 duration.'), c2: V('Caster takes 3 ordinary damage (Barrier/Armor first).') },
      steps: { 0: V('CauseDeathMark FrontEnemy -> enemyFront.'), 1: V('CauseDeathMark LastEnemy -> enemyLast.'), 2: V('Damage Self 3 -> damage allySelf base 3.') },
      branches: { main: V('Single unconditional branch.') } },
    'weapon:1147': { test: 'tests/unit/gowLaneL5B02.test.ts', extra: [...extraBase],
      en: 'weapon 1147 Crypt Keeper: gowhead English "Death Mark an enemy. Deal [Magic + 1] true damage to all enemies below them, boosted by enemy Death Marks. [x3]", cost 13 Purple, 7444 + gw_CryptKeeper.',
      native: 'spell 7444 Target Enemy: CauseDeathMark FromTarget; CountSpecificStatusEffect AllEnemies deathmark Amount 300; TrueDamage BelowTarget UseCounterForAmount Amount 1 SPM 1.',
      dims: common({ id: 'Weapon 1147 -> spell 7444, cost 13, Purple; both aliases.', target: 'Chosen enemy marked and untouched; every living enemy below it takes damage; last enemy chosen -> nobody below.', formula: 'True damage Magic+1+3*marks.', boost: 'x3 per Death Marked enemy counted after step 0 (1 mark +3, 3 marks +9; pre-existing marks count).', status: 'Death Mark ' + DUR + ' Warded chosen enemy gets no mark.', order: 'Mark -> count -> damage native order.' }),
      clauses: { c1: V('Chosen enemy Death Marked (R004).'), c2: V('True damage Magic+1 to all enemies below.'), c3: V('[x3] per Death Marked enemy.') },
      steps: { 0: V('CauseDeathMark FromTarget.'), 1: V('CountSpecificStatusEffect deathmark 300 -> modifier multiplier 3 enemyStatusCount.'), 2: V('TrueDamage BelowTarget -> enemyBelowTarget trueDamage.') },
      branches: { main: V('Single unconditional branch.') } },
  },
  b03: {
    'troop:6229': { test: 'tests/unit/gowLaneL5B03.test.ts', extra: [...extraBase, r001],
      en: 'troop 6229 Sand Cobra: spell 7371 "Poison, Disease, and Stun a random enemy.", cost 6 Brown.',
      native: 'spell 7371 Target None: CauseDisease RandomEnemy; CausePoison FromPrevious; CauseStun FromPrevious.',
      dims: common({ id: 'Troop 6229 -> spell 7371, cost 6, Brown.', target: 'One random living enemy (varies over 30 seeds; dead never picked).', cond: 'Random pick via seeded RNG.', status: 'Disease/Stun ' + DUR + ' Poison never self-cleanses; Disease-immune blocks Disease; Invulnerable blocks all.', order: 'Disease -> Poison -> Stun native order (R001); Stun last cannot strip immunity first.' }),
      clauses: { c1: V('One random enemy Diseased, Poisoned, Stunned; R004 durations.') },
      steps: { 0: V('CauseDisease RandomEnemy -> enemyRandom disease.'), 1: V('CausePoison FromPrevious -> lastTarget poison.'), 2: V('CauseStun FromPrevious -> lastTarget stun.') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6217': { test: 'tests/unit/gowLaneL5B03.test.ts', extra: [...extraBase, r001],
      en: 'troop 6217 Creeper: spell 7359 "Deal [Magic + 3] damage to an enemy and Disease them.", cost 7 Red.',
      native: 'spell 7359 Target Enemy: CauseDisease FromTarget Amount 1; Delay 925; Damage FromTarget Amount 3 SPM 1.',
      dims: common({ id: 'Troop 6217 -> spell 7359, cost 7, Red.', target: 'Chosen enemy only.', formula: 'Magic+3 (armor first): magic 0 -> 3, magic 8 -> 11.', status: 'Disease ' + DUR + ' Disease-immune target still takes damage.', order: 'Disease -> Damage native order; Barrier absorbs damage but Disease lands; lethal hit after Disease.' }),
      clauses: { c1: V('Chosen enemy Diseased then takes Magic+3.') },
      steps: { 0: V('CauseDisease FromTarget.'), 1: V('Delay 925: presentation pause only; real cast shows Disease then damage with no event in between.'), 2: V('Damage FromTarget 3/1.') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6924': { test: 'tests/unit/gowLaneL5B03.test.ts', extra: [...extraBase],
      en: 'troop 6924 Heart of Rage: spell 8393 "Enrage all Allies and Enemies.", cost 6 Red.',
      native: 'spell 8393 Target None: CauseEnraged AllAllies Amount 1; CauseEnraged AllEnemies.',
      dims: common({ id: 'Troop 6924 -> spell 8393, cost 6, Red.', target: 'Every living ally incl. caster, then every living enemy.', status: 'Enraged no timer (6 turn starts), ends when the holder deals skull damage (R004, gowLaneL5R3); Blessed enemy immune; re-apply refreshes (alias counted).', order: 'Allies then enemies (native order).' }),
      clauses: { c1: V('All allies and enemies Enraged; R004 duration.') },
      steps: { 0: V('CauseEnraged AllAllies -> rage allyAll.'), 1: V('CauseEnraged AllEnemies -> rage enemyAll.') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6546': { test: 'tests/unit/gowLaneL5B03.test.ts', extra: [...extraBase, r001],
      en: 'troop 6546 Senita: spell 7740 "Deal [Magic + 6] true damage to the last enemy. Enrage them.", cost 12 Green/Red.',
      native: 'spell 7740 Target None: CauseEnraged LastEnemy Amount 1; TrueDamage LastEnemy Amount 6 SPM 1.',
      dims: common({ id: 'Troop 6546 -> spell 7740, cost 12, Green/Red.', target: 'Last living enemy (dead last -> 12).', formula: 'True damage Magic+6 ignoring armor.', status: 'Enraged no timer, ends on the holder\'s skull damage (R004, gowLaneL5R3).', order: 'Enrage -> TrueDamage native order (R001); lethal true damage defeats it.' }),
      clauses: { c1: V('Last enemy takes Magic+6 true damage.'), c2: V('Last enemy Enraged (native: before damage).') },
      steps: { 0: V('CauseEnraged LastEnemy -> rage enemyLast.'), 1: V('TrueDamage LastEnemy 6/1.') },
      branches: { main: V('Single unconditional branch.') } },
    'weapon:1072': { test: 'tests/unit/gowLaneL5B03.test.ts', extra: [...extraBase],
      en: 'weapon 1072 Spider\'s Kiss: gowhead English "Entangle the first Enemy, and deal [Magic + 2] true damage.", cost 14 Purple, 7185 + gw_SpidersKiss.',
      native: 'spell 7185 Target None: CauseEntangle FrontEnemy; TrueDamage FrontEnemy Amount 2 SPM 1.',
      dims: common({ id: 'Weapon 1072 -> spell 7185, cost 14, Purple; both aliases.', target: 'First living enemy (dead front -> 11).', formula: 'True damage Magic+2 ignoring armor.', status: 'Entangle ' + DUR + ' Invulnerable front takes no Entangle.', order: 'Entangle -> TrueDamage native order.' }),
      clauses: { c1: V('Front enemy Entangled then Magic+2 true damage.') },
      steps: { 0: V('CauseEntangle FrontEnemy -> enemyFront.'), 1: V('TrueDamage FrontEnemy 2/1.') },
      branches: { main: V('Single unconditional branch.') } },
  },
  b04: {
    'troop:6219': { test: 'tests/unit/gowLaneL5B04.test.ts', extra: [...extraBase, r001],
      en: 'troop 6219 Moa: spell 7361 "Deal [Magic + 3] damage to an enemy and Stun them.", cost 7 Yellow.',
      native: 'spell 7361 Target Enemy: CauseStun FromTarget Amount 1; Delay 1000; Damage FromTarget Amount 3 SPM 1.',
      dims: common({ id: 'Troop 6219 -> spell 7361, cost 7, Yellow.', target: 'Chosen enemy only.', formula: 'Magic+3: magic 0 -> 3, magic 8 -> 11.', status: 'Stun ' + DUR + ' Stun-immune (Thick Head) still takes damage.', order: 'Stun -> Damage native order; Barrier absorbs damage but Stun lands; lethal.' }),
      clauses: { c1: V('Chosen enemy Stunned then takes Magic+3.') },
      steps: { 0: V('CauseStun FromTarget.'), 1: V('Delay 1000: presentation pause only; real cast shows Stun then damage with no event in between.'), 2: V('Damage FromTarget 3/1.') },
      branches: { main: V('Single unconditional branch.') } },
    'troop:6222': { test: 'tests/unit/gowLaneL5B04.test.ts', extra: [...extraBase, r001],
      en: 'troop 6222 Khopeshi: spell 7364 "Pull an Enemy to first position and Stun them.", cost 7 Blue.',
      native: 'spell 7364 Target Enemy: CauseStun FromTarget Amount 1; Delay 1000; TroopOrderFront FromTarget.',
      dims: common({ id: 'Troop 6222 -> spell 7364, cost 7, Blue.', target: 'Chosen enemy; others keep relative order.', status: 'Stun ' + DUR + ' Stun-immune enemy still pulled to front.', order: 'Stun -> TroopOrderFront native order; front enemy chosen stays first.' }),
      clauses: { c1: V('Chosen enemy Stunned and moved to first position.') },
      steps: { 0: V('CauseStun FromTarget.'), 1: V('Delay 1000: presentation pause only; real cast shows Stun then reposition with no event in between.'), 2: V('TroopOrderFront FromTarget -> reposition lastTarget front.') },
      branches: { main: V('Single unconditional branch.') } },
  },
};
for (const [b, spec] of Object.entries(specs)) {
  for (const s of Object.values(spec)) { s.decision = 'accept'; s.rule = { ...rule, note: 'Official status guide: status semantics (Barrier, Silence, Stun, Disease, Death Mark, Enrage, Submerged, cumulative cleanse chance via Cursed/Lycanthropy entries).' }; }
  fs.writeFileSync(`${dir}/spec-r3-${b}.json`, JSON.stringify(spec, null, 1));
}
console.log('written', Object.keys(specs).join(','));
