/**
 * Summon pools for native SummoningKingdom* steps, taken from data/raw/troops.gow.en.json KingdomId (roster troops only).
 * The roster's zh kingdom name merges faction kingdoms into their parent (e.g. Dripping Caverns 3058 -> Grosh-Nak),
 * so randomOfKingdom(<zh name>) over-includes; skills whose native step names a kingdom id use these lists (sa-E, L1 r4).
 */
export const RAW_KINGDOM_POOLS = {
  3000: ['LavaGates', 'ToxAndSion', 'PrisonerLuther', 'ScoriaGiant-born', 'SteamTroll', 'DragonlordLuther', 'GhostOgre', 'Salamandria', 'Meteoridan', 'CinderhandGoblin', 'JeweledGolem', 'LavaWorm', 'Pyrophemus', 'AceOfWands', 'FireBeetle', 'FlameRhynax', 'SulfurSlime', 'Ogress', 'VolcanicGolem', 'Amarok', 'OgrakShaman', 'Stone-Biter', 'LavaTroll', 'Rhynaggor', 'Igneus', 'Pyggra', 'FireBomb', 'FlameTroll', 'Infernus', 'GogAndGud', 'ObsidianTitan', 'FireLizard', 'LavaElemental', 'Gob-Chomper', 'Elf-Eater', 'FortressGate', 'Luther', 'Sheggra', 'StoneGiant', 'Ettin', 'Rhynax', 'Ogre'],
  3001: ['NAV-1057', 'DRIDR-8000', 'WEEZL-300', 'RatchetCogbolt', 'LOCK-1887', 'WATTS-1927', 'ImmortalTitanius', 'FIXIT-5000', 'TeslasEngine', 'GeneralEdison', 'AceOfRunes', 'BORK-3000', 'TinkerDwarf', 'Limpet-bot', 'TheChariot', 'TheSparkinator', 'Researcher', 'Ironhawk', 'NUTCRKR-1225', 'S.O.L.A.R', 'MechaRat', 'P4-NTH4', 'CarlsonMarshall', 'ROVER-300', 'TINA-9000', 'TED-1000', 'ClockworkSphinx', 'Tesla', 'SentryBot', 'ClockworkKnight', 'DRACOS-1337', 'Bombot', 'RoyalEngineer', 'Ghiralee', 'TANKBOT-2000', 'Sparkgrinder', 'Carnex', 'FlameCannon', 'SteamTurret', 'Alchemist', 'Musketeer'],
  3003: ['Ariosa', 'LapinaCharlatan', 'Sonata', 'LapinaLancer', 'ZombieGoat', 'TenOfCups', 'Narcithus', 'ImmortalCaprichor', 'DoeStoneshatter', 'Badgerkin', 'Caprichor', 'SatyrTrickster', 'FallenSatyr', 'Beltane', 'VoicelessGolem', 'TheWildKing', 'SkyGoat', 'TheBurrowWarden', 'PoxHare', 'Pan', 'Argos', 'SileniGuard', 'Rubitressa', 'SatyrHunter', 'Starflower', 'LapinaExplorer', 'Caprinicus', 'Piper', 'TheWildQueen', 'KingSilenus', 'Nax', 'Nyx', 'WarGoat', 'SatyrMusician', 'BunniNog', 'Faunessa', 'Sylvasi', 'Elwyn', 'TheSilentOne', 'BladeDancer', 'Siren', 'Nymph', 'Satyr'],
  3004: ['ImmortalTrogolin', 'LordGobthe', 'CountGobula', 'ZargsBoomPile', 'MokTheCannon-Rider', 'GoblinPickpocket', 'Gloomhob', 'Murk,Lurk,AndDurk', 'BombRider', 'Slughoarder', 'PriestOfNilbog', 'GoblinBomber', 'BrianTheClucky', 'TheFool', 'FaerieGobmother', 'FlamingOni', 'Fundingus', 'Smashedmouth', 'Rogueling', 'Goblette', 'DynamiteGoat', 'Toadsqueezer', 'Stringfiddler', 'HighKingIrongut', 'TurtleCannon', 'Hellcackle', 'Gorbil', 'QueenGrapplepot', 'PrincessFizzbang', 'Scavenger', 'Bugbear', 'GiantToadstool', 'SirSnothelm', 'NobendBrothers', 'GoblinRocket', 'Hobgoblin', 'BrianTheLucky', 'GoblinKing', 'BlackBeast', 'BoarRider', 'GoblinShaman', 'Goblin'],
  3006: ['GriffonCaptain', 'SirGeoffreyTheFallen', 'Raquel', 'ImmortalZachariel', 'SeabornKnight', 'Orrissea', 'TheFallenKnight', 'JusticeTarot', 'AldricTheFrostbound', 'DragonCommander', 'BrassDrake', 'GuardianOfLaw', 'Militiaman', 'TheGuardianDragon', 'MysteriousHero', 'Eleanor', 'KnightErrant', 'RelicKnight', 'GameWarden', 'SpectralColossus', 'UlfHarrigan', 'UlfsMascot', 'HauntedGuardian', 'SirQuentinHadley', 'KnightCaptain', 'Man-at-Arms', 'SirEbonheart', 'CourtJester', 'QueensHerald', 'Vanguard', 'ChampionOfAnu', 'SerCygnea', 'SirGwayne', 'QueenYsabelle', 'Innkeeper', 'DragonKnight', 'Warhound', 'Peasant', 'Tau', 'ShadowDragon', 'KnightCoronet', 'GriffonKnight', 'WolfKnight', 'LanceKnight'],
  3009: ['KingElbormor', 'Siobhan', 'ElvenNoble', 'Cosmo', 'ImmortalSelene', 'CorruptedCrystalem', 'WoodRot', 'Leucithrax', 'GuardianSpirit', 'LioraMistveil', 'Mistlark', 'ArcaneSabercat', 'SirAiluin', 'CrystalEggs', 'HeraldOfKrystenax', 'Amethialas', 'FloraFawn', 'MoonMage', 'SwordMaiden', 'Tannenbaum', 'MoonPhoenix', 'TheMagician', 'Forgemistress', 'StarryMage', 'SapphireKnight', 'WillOfNysha', 'Grimcorn', 'LordEhrondil', 'SilverOak', 'Willow', 'Arcanus', 'Hind', 'QueenAurora', 'Wisp', 'Krystenax', 'TheSilvermaiden', 'PrincessElspeth', 'Unicorn', 'Enchantress', 'ElvenBard', 'Swordmaster', 'SilverDrakon'],
  3010: ['RangerEvgeniy', 'PoisonedUrsidae', 'AbominableTroll', 'VelesStormborn', 'IvarLongclaw', 'SkeletalUrska', 'Bieska', 'Bearlock', 'Theodorevich', 'Ursky', 'IronVlasta', 'SpiritOfRage', 'Wereverine', 'Ursuvius', 'SnowyOwlbear', 'EnragedKurandara', 'Kurandara', 'ShadeOfKurandara', 'PrinceBarislav', 'BlackBjörn', 'PossessedUrska', 'Berengari', 'UrskayanBlue', 'UrskaDruid', 'Urskula', 'UrskaDragoon', 'Mammoth', 'Doomclaw', 'UrskaSavage', 'BabaYaga', 'YagasHut', 'KingMikhail', 'CorruptedUrska', 'Vodyanoi', 'Domovoi', 'Urskatyr', 'Leshy'],
  3011: ['Fionnuala', 'FrostSpider', 'Helilya', 'Boudicca', 'Muireann', 'ImmortalGlaycia', 'YetiCub', 'Moonfeather', 'FeyDragoon', 'TheBestialFey', 'DaughterOfTime', 'Rukh', 'TheHighPriestess', 'KingOfRavens', 'Sapphirax', 'Saga', 'IceOrca', 'Grimmoira', 'Ullor', 'Cernunnos', 'Frostfeather', 'DaughterOfIce', 'SnowPanther', 'DoomOfIce', 'Freya', 'FrostArcher', 'Skadi', 'Snow-Hunter', 'FrostLizard', 'SnowGuardian', 'Frostling', 'IceGolem', 'WinterWolf', 'Borealis', 'QueenMab', 'Tassarion', 'Yeti', 'WinterKnight', 'Jackelope', 'SnowSprite'],
  3014: ['TheSoulKnight', 'Sarathiel', 'AngelicaTheSeeker', 'SirHector', 'Peregrine', 'HolyArcher', 'ImmortalLibara', 'TwoOfSwords', 'Retribution', 'TheBlessedMaiden', 'Temperance', 'Amatiel', 'Solarithus', 'Dominion', 'CommanderDawnheart', 'HighCleric', 'Witchfinder', 'PriestessOfLight', 'TheTopazGiant', 'Libara', 'Mechamare', 'Ascendance', 'UrielleTheGuardian', 'Quatramanus', 'TheArchdeva', 'SirAlamir', 'Virtue', 'Patience', 'Solari', 'Gravitas', 'ChampionOfGaard', 'HolySt.Astra', 'AngryMob', 'SisterSuperior', 'StatueOfSt.Veritas', 'WarCleric', 'HighPaladin', 'Bishop', 'GaardsAvatar', 'Penitent', 'GrandInquisitor', 'Celestasia', 'Templar', 'LadySapphira', 'Moloch', 'SacredGuardian', 'ArchonStatue', 'Paladin', 'Priestess'],
  3015: ['Wisterina', 'ImmortalMonstera', 'Vinepyre', 'LadyFlorella', 'QueenOfSwords', 'TheDecayingQueen', 'Gladius', 'ImmortalVirago', 'Adelwing', 'GiantBadger', 'ElementalSentinel', 'Grimfeather', 'Virago', 'DaughterOfYasmine', 'Treekin', 'TheEmeraldGiant', 'LordArchimedus', 'Crystalynx', 'ThornScout', 'TheWerestag', 'EarthDreamer', 'LordBelanor', 'Faemark', 'DandyLion', 'KingBloodwood', 'WoodRhynax', 'KingAvelorn', 'VineMarten', 'Ironbark', 'OwlRider', 'ForestTroll', 'YasminesChosen', 'Aurai', 'Archdruid', 'Sylvanimora', 'ThornKnight', 'LadyAnariel', 'GreenSeer', 'Hippogryph', 'Rowanne', 'GloomLeaf', 'Treant', 'Owlbear', 'Dryad', 'GladeWarden'],
  3017: ['Vizinium', 'BloodSpore', 'OkraNosTheSleeper', 'Abraxas', 'ShadowWraith', 'TheSlimeDragon', 'TheCartographer', 'BookOfWitches', 'Tempurath', 'TriTerror', 'AceOfSwords', 'EldritchDisciple', 'TheElderDragon', 'DeathlockDreilak', 'TheAmethystGiant', 'Uvhash-Ka', 'EldritchMinion', 'Draxxius', 'BookOfSecrets', 'KeeperOfLore', 'EldritchGuardian', 'Netherhound', 'Ahrimas', 'CorruptMagus', 'VashDagon', 'WallOfTentacles', 'Medea', 'GelatinousCube', 'ZuulGoth', 'TomeOfEvil', 'Tzathoth', 'Hellspawn', 'Myzmer', 'VoidPortal', 'DarkTroll', 'SacrificialPriest', 'GreenSlime', 'Cthyryzyx', 'Ferit', 'Abhorath', 'AncientHorror', 'Warlock', 'Acolyte', 'Golem'],
  3018: ['Hematrax', 'Shargral', 'Warfang', 'MorZarn', 'KingOfSwords', 'KragRaxBloodskull', 'ImmortalAngRak', 'TenOfRunes', 'DaeDrak', 'OrcRogue', 'MouthOfZorn', 'EyeOfArges', 'TrkNala', 'RokGarTheGuardian', 'TuskRaider', 'ArmoredBoarlet', 'WarDrok', 'BrawlmasterBurNakh', 'WarWolf', 'GorThrum', 'ShadeOfZorn', 'BorGakk', 'FistOfZorn', 'VorKarn', 'DireBoar', 'SolZara', 'Gargantaur', 'Drake', 'OrcVeteran', 'Ogryn', 'FelDras', 'ArmoredBoar', 'KruargTheDread', 'Wyvern', 'GarNok', 'DarkSong', 'DrakeRider', 'Cyclops', 'Summoner', 'Orc'],
  3020: ['Amenhotrex', 'Merneith', 'SekhitePriestess', 'HorusiteChampion', 'BarrowLord', 'PharaohKhafru', 'TawaritePriestess', 'Gynosphinx', 'SkellyCat', 'AssessorOfMahat', 'SetauriGladius', 'Rath-Amon', 'VaultGuard', 'JakalTheGuardian', 'CarrionCrow', 'TombKnight', 'PharaohNefertani', 'Ankhnum', 'Tutankhatmun', 'Ankhekt', 'Apophisis', 'PharaohHound', 'Morterra', 'WallOfBones', 'Necrezza', 'BastitePriestess', 'Pharos-Ra', 'BoneScorpion', 'MummifiedKing', 'SettiteWarrior', 'AnubiteWarrior', 'BoneDragon', 'Aziris', 'Alastair', 'KeeperOfSouls', 'WarSphinx', 'Revenant', 'Wight', 'Skeleton'],
  3022: ['ImmortalByblios', 'TwistedHag', 'GreenHag', 'QueenOfRunes', 'MotherMalice', 'ChampionOfRot', 'ToxicHag', 'VenomousTroll', 'OcularenEgg', 'LordDesollatus', 'AnointedChampion', 'UndeadLion', 'Nebuladryx', 'SeaHag', 'Carmina', 'Shadowbeast', 'ConsortOfDarkness', 'HornedHag', 'Yarrow', 'SisterOfNightmares', 'SisterEbony', 'BlindGuardian', 'MotherOfDarkness', 'GruzTheUndefeated', 'CorruptTroll', 'Bael', 'ThePossessedKing', 'Umbraxis', 'Executioner', 'Magnus', 'SisterOfShadows', 'MerchantPrince', 'Troglodyte', 'GiantToad', 'NightHag', 'Remnant', 'CorruptSorceress', 'SeaTroll', 'AnointedOne', 'Psion', 'Dimetraxia', 'Watcher', 'DarkMaster', 'Hag', 'Thrall'],
  3023: ['Yohaulticetl', 'Cassoryx', 'Cinereous', 'Mayahuel', 'CrestedAva', 'FisherKing', 'Kukulkan', 'SparrowKnight', 'Egris', 'Ehecatl', 'Stormcrow', 'Rubirath', 'Totec', 'EagleOwl', 'Ostryx', 'Swanmay', 'TheSun', 'Metztli', 'HighPriestessChazka', 'Quetzalma', 'Zilopochtli', 'Lyriath', 'PavosDawnwind', 'HarpyEagle', 'DoomOfLight', 'Phoenicia', 'Ixchel', 'WindArcher', 'Taloca', 'Stormsinger', 'Strygik', 'Sunbird', 'PrinceAzquila', 'Garuda', 'Tezca', 'JaguarWarrior', 'Sylph', 'Owleth', 'Heronath', 'Chupacabra'],
  3024: ['Voidjaw', 'TheSandstoneSentinel', 'DenwenTheWanderer', 'DesertOx', 'TheCragMaw', 'ImmortalScoprio', 'Al-Mundhir', 'MonstrousSentinel', 'Hornwing', 'MantisMage', 'TheHermit', 'Khronos', 'Stoneshell', 'Scoprio', 'Topasarth', 'FakyrTheWise', 'SkyScorpion', 'Obregonia', 'Bahir', 'DesertWorm', 'TyranAndRex', 'Trihorn', 'ShahbanuVespera', 'Scarabi', 'Sharptooth', 'Sandrunner', 'Agave', 'Saguaro', 'Senita', 'SandScuttler', 'Scorpius', 'AncientGolem', 'DesertTroll', 'RockSpirit', 'MadProphet', 'DragonCruncher', 'SandShark', 'TheGreatMaw', 'Marid', 'Ifrit', 'Djinn', 'DustDevil', 'Roc'],
  3025: ['Warmadillo', 'Gindibu', 'CaravanCamel', 'DragonknightAmira', 'Mantichoras', 'AlaAl-Din', 'ImmortalRaqiyah', 'LionCommander', 'ManeCourser', 'Geryon', 'SandCat', 'OrpheusPriestess', 'CorbenHalf-Elf', 'RegentKhalif', 'ServantOfTheDao', 'LeonisTower', 'TheEmperor', 'DarkDjinnBottle', 'Dao', 'FlameOfAnu', 'WarElephant', 'ManticoreProtector', 'ManticoreCub', 'GeneralSuladin', 'KhatibTahir', 'TigrakiWarrior', 'Wazir', 'Moneylender', 'DivineIshbaala', 'VoiceOfOrpheus', 'MonsterMuncher', 'Warhawk', 'Falconer', 'SnakeCharmer', 'DesertMantis', 'WanderingMonk', 'SandCobra', 'PrideGuard', 'EmperorKhorvash', 'Amira', 'Manticore', 'LionPrince', 'TheDevoted', 'Khopeshi'],
  3027: ['BokSingefur', 'RagingBull', 'ImmortalTauraeus', 'Creteus', 'GorrMurktooth', 'Hornbreaker', 'VigilantShade', 'TaurosGladiator', 'Redreaver', 'KooTheBrave', 'MazeGuardian', 'Judgement', 'KingStormgard', 'Spirittooth', 'Tauraeus', 'TaurosGuardian', 'Stormchaser', 'Pyrohydra', 'TheLordOfSlaughter', 'Bullygnoll', 'QueenMoonclaw', 'Bullserker', 'Ridgeback', 'BaneJaw', 'Earthcaller', 'FestivalCow', 'Cloudstalker', 'MidgeSwarm', 'ChiefStronghorn', 'Hyena', 'Bulette', 'Mongo', 'KetrasTheBull', 'Minogor', 'SavageHunter', 'WingedBison', 'WildFang', 'Skeleros', 'Hydra', 'Sunweaver', 'Gorgon', 'Gnoll', 'Soothsayer', 'Tauros'],
  3028: ['Ciaran', 'DuskWitch', 'KingEquustis', 'Eridana', 'Astrotaur', 'CentaurElder', 'Discordia', 'ImmortalSagittarian', 'Zebrataur', 'WingedDonkey', 'Hippolyta', 'Ogretaur', 'TwoOfWands', 'TheCattauriKing', 'CattauriWarrior', 'Deathgaunt', 'AxeBeak', 'Chiron', 'Sagittarian', 'Centuragon', 'Oneiros', 'AstralMother', 'Orrery', 'Auspecia', 'Thaumataur', 'GuardianOfTheFields', 'Plainsjumper', 'Nightwing', 'HorseLord', 'Herne', 'OrionsHerald', 'TheWorldbreaker', 'Artema', 'Anthea', 'Moa', 'AstralSpirit', 'BulTauros', 'Ragnagord', 'Atlanta', 'Orion', 'Herdmaster', 'Pegasus', 'StarGazer', 'CentaurScout'],
  3029: ['ErendrielDarkweave', 'KnightOfCups', 'TheWebbedPrince', 'DarkWitch', 'ImmortalMaratus', 'Scrollweaver', 'Belcerulea', 'DuskOwlbear', 'ShadowBeetle', 'Mandragora', 'SplinteredGolem', 'DarkAlchemist', 'LeapingSpider', 'TheSilkenQueen', 'TheSpiderThrone', 'SilkenFang', 'SeekraDarkwood', 'BoundMage', 'AceOfCups', 'Mechweaver', 'ArchproxyYvendra', 'AransiTheGuardian', 'Devourer', 'NightSpider', 'ArachnaeanWatcher', 'Malcandessa', 'Arachnataur', 'Tarantella', 'ArachnaeanWeaver', 'TheWidowQueen', 'TombSpider', 'Spinnerette', 'Cocoon', 'Shadowblade', 'SpiderKnight', 'TalRae', 'SpiderSwarm', 'Dokkalfar', 'GiantSpider', 'Tyri', 'Webspinner', 'SpiderQueen', 'NightTerror', 'DarkMaiden', 'Reaver'],
  3030: ['HanXin', 'Xuanwu', 'Yue-She', 'TenOfSwords', 'Orchidius', 'LionOfYaoGuai', 'ImmortalLucifa', 'ShejiShi', 'Pandallista', 'Tianlong', 'TheTurquoiseEmperor', 'Tuzi', 'Zhuque', 'HoundOfLiang', 'WuHao', 'MoshuTheGuardian', 'SkyMage', 'Huanglong', 'HoundOfYaoGuai', 'Baihu', 'PandaskaMage', 'Tuliao', 'Qilin', 'MoonRabbit', 'DoomOfDarkness', 'TianYi', 'SifuYuan', 'CrimsonArrow', 'PandaskaGuard', 'EmperorLiang', 'YaoGuai', 'Penglong', 'Diviner', 'Spearmaster', 'XiongMao', 'MonkeyDisciple', 'Spellblade', 'Zhenniao'],
  3035: ['RhonaBittershield', 'CaveCrawler', 'CaveMole', 'Mrs.Krinkle', 'KhormacTheRestless', 'ForsakenGuardian', 'KingOfRunes', 'Gormungandr', 'DugallRamhorn', 'IcyPortal', 'GhostKingGrimhorn', 'LostWarrior', 'LivingRime', 'Garnetaerlin', 'DhrakSmith', 'FrozenShieldbreaker', 'BoneboundDredge', 'Arcturion', 'MoiraCragheart', 'Kryshound', 'Obsidius', 'BlackfireCannon', 'CursedEffigy', 'DoomOfStone', 'GriffStonefeather', 'FallenValdis', 'KingBloodhammer', 'Glaycion', 'IceTroll', 'Gemhammer', 'Bonebinder', 'IceGoblin', 'SlayerGhost', 'DwarvenZombie', 'IceWorm'],
  3036: ['ImmortalThalassa', 'Tempestus', 'Ipanema', 'Balearic', 'TidalDancer', 'ToxicPuffer', 'MaelstromDagoNath', 'Caspian', 'BloomManatee', 'KingOfCups', 'DagoNath', 'Treviamus', 'DrownedWanderer', 'DraugrKnight', 'TritonGuardMera', 'MantaRaider', 'SeaScavenger', 'Triton', 'Anglerfin', 'Piscea', 'Wereshark', 'Kharybdis', 'Cyrene', 'Tuskor', 'Axolotl', 'Crysturtle', 'Nereida', 'Merknight', 'Aquaticus', 'Mervorax', 'Mermaid', 'Nimue', 'MantisShrimp', 'Undine', 'CoralGolem', 'Leviathan', 'Waverider', 'Azura', 'Lamprey', 'Merlion', 'Kuotani', 'Hippocampus', 'GiantCrab'],
  3037: ['ImmortalZephaar', 'MaidenOfPain', 'FelineOfEnvy', 'BaneOfAmbition', 'TenOfWands', 'ImmortalAbaddon', 'TheBaneOfValor', 'StingBat', 'DarkHerald', 'Eklipsos', 'TheBaneOfMercy', 'WarMachine', 'AnimusOfEnvy', 'Despond', 'AbjectOfDespond', 'MaidOfEnvy', 'TheScourgeOfHonor', 'IndolatorOfSloth', 'GaelSpiritwhisperer', 'EnvoyOfPride', 'BrokerOfGreed', 'Glutmaw', 'QueenOfSin', 'SoldierOfWrath', 'SibylOfLust', 'Lust', 'Wrath', 'Pride', 'Barghast', 'Gluttony', 'Greed', 'Envy', 'Sloth'],
  3051: ['KoboldThief', 'Emperinazara', 'KoboldMagi', 'KoboldKnight', 'Kobold'],
  3058: ['BlackOoze', 'Shoggorath', 'OchreJelly', 'Cloakmantle', 'RockSquid'],
  3080: ['Tetramorph', 'Blackthorn', 'CorruptedCycad', 'TempestBallista', 'WaterbornTemplar', 'Chrysantherax', 'ImmortalAquaria', 'ImmortalEmpyrion', 'Emberclaw', 'Ignarion', 'FirebornPaladin', 'FirebornLynx', 'PrinceBasalt', 'WaterbornScribe', 'QueenAsh', 'DoomedGargoyle', 'Aquaria', 'TheUmbralGiant', 'NaturebornHunter', 'NatureWeird', 'WaterWeird', 'Hawthorn', 'ValiantPyrea', 'StonebornLion', 'WaterbornOwl', 'FirebornEagle', 'NaturebornWolf', 'TheLovers', 'Kalika', 'KingHeliodor', 'NexusPortal', 'Shayle', 'WaterbornPriestess', 'FirebornWarrior', 'NaturebornWarden'],
  3082: ['Seditius', 'TheTombkeeper', 'Sanguinette', 'Rockraptor', 'TheDarkOracle', 'Skarn', 'Mudwalker', 'ClayFiend', 'ImmortalTerra', 'Goethite', 'Isban', 'Groevanga', 'Ctharrasque', 'DragonstoneGuardian', 'PetrifiedTreant', 'StonePanther', 'TheColossus', 'Morganite', 'StoneMefyt', 'Craghound', 'Petrahulk', 'StoneZombie', 'Adakite', 'Chalcedony', 'Tourmaline', 'Xenith', 'TheTower', 'EternalSentinel', 'Nabassu', 'Czernobog', 'HeraldOfTorpor', 'PetrifiedGolem', 'HellstoneGate'],
  3083: ['AlabasterKnight', 'Obsidiaxas', 'ChromiteSphinx', 'OnyxGargoyle', 'DarkGolem'],
  3084: ['Liekki', 'Velosia', 'DarkSpirit', 'Kumiko', 'WulfGheist', 'SpiritcallerLila', 'SpiritOfLuck', 'Azaleus', 'ExiledWargare', 'Ragepaw', 'SoulSummoner', 'Aguara', 'Foxglove', 'KitTheSly', 'Stellarix', 'VulpineWatcher', 'VulpineChampion', 'Duelist', 'SableSpiritbane', 'ToddGreenwood', 'Fenix', 'VulpphireHunter', 'TheWheelOfFortune', 'FennecMage', 'FennecThief', 'Voidcaller', 'Harper', 'Vulperus', 'RedFox', 'VulpineMage'],
} as const satisfies Record<number, readonly string[]>;
export const rawKingdomPool = (id: keyof typeof RAW_KINGDOM_POOLS): string[] => [...RAW_KINGDOM_POOLS[id]];
