/**
 * Summon pools for native SummoningKingdom* steps, taken from data/raw/troops.gow.en.json KingdomId (roster troops only).
 * The roster's zh kingdom name merges faction kingdoms into their parent (e.g. Dripping Caverns 3058 -> Grosh-Nak),
 * so randomOfKingdom(<zh name>) over-includes; skills whose native step names a kingdom id use these lists (sa-E, L1 r4).
 */
export const RAW_KINGDOM_POOLS = {
  3058: ['BlackOoze', 'Shoggorath', 'OchreJelly', 'Cloakmantle', 'RockSquid'],
  3018: ['Hematrax', 'Shargral', 'Warfang', 'MorZarn', 'KingOfSwords', 'KragRaxBloodskull', 'ImmortalAngRak', 'TenOfRunes', 'DaeDrak', 'OrcRogue', 'MouthOfZorn', 'EyeOfArges', 'TrkNala', 'RokGarTheGuardian', 'TuskRaider', 'ArmoredBoarlet', 'WarDrok', 'BrawlmasterBurNakh', 'WarWolf', 'GorThrum', 'ShadeOfZorn', 'BorGakk', 'FistOfZorn', 'VorKarn', 'DireBoar', 'SolZara', 'Gargantaur', 'Drake', 'OrcVeteran', 'Ogryn', 'FelDras', 'ArmoredBoar', 'KruargTheDread', 'Wyvern', 'GarNok', 'DarkSong', 'DrakeRider', 'Cyclops', 'Summoner', 'Orc'],
  3030: ['HanXin', 'Xuanwu', 'Yue-She', 'TenOfSwords', 'Orchidius', 'LionOfYaoGuai', 'ImmortalLucifa', 'ShejiShi', 'Pandallista', 'Tianlong', 'TheTurquoiseEmperor', 'Tuzi', 'Zhuque', 'HoundOfLiang', 'WuHao', 'MoshuTheGuardian', 'SkyMage', 'Huanglong', 'HoundOfYaoGuai', 'Baihu', 'PandaskaMage', 'Tuliao', 'Qilin', 'MoonRabbit', 'DoomOfDarkness', 'TianYi', 'SifuYuan', 'CrimsonArrow', 'PandaskaGuard', 'EmperorLiang', 'YaoGuai', 'Penglong', 'Diviner', 'Spearmaster', 'XiongMao', 'MonkeyDisciple', 'Spellblade', 'Zhenniao'],
  3000: ['LavaGates', 'ToxAndSion', 'PrisonerLuther', 'ScoriaGiant-born', 'SteamTroll', 'DragonlordLuther', 'GhostOgre', 'Salamandria', 'Meteoridan', 'CinderhandGoblin', 'JeweledGolem', 'LavaWorm', 'Pyrophemus', 'AceOfWands', 'FireBeetle', 'FlameRhynax', 'SulfurSlime', 'Ogress', 'VolcanicGolem', 'Amarok', 'OgrakShaman', 'Stone-Biter', 'LavaTroll', 'Rhynaggor', 'Igneus', 'Pyggra', 'FireBomb', 'FlameTroll', 'Infernus', 'GogAndGud', 'ObsidianTitan', 'FireLizard', 'LavaElemental', 'Gob-Chomper', 'Elf-Eater', 'FortressGate', 'Luther', 'Sheggra', 'StoneGiant', 'Ettin', 'Rhynax', 'Ogre'],
  3017: ['Vizinium', 'BloodSpore', 'OkraNosTheSleeper', 'Abraxas', 'ShadowWraith', 'TheSlimeDragon', 'TheCartographer', 'BookOfWitches', 'Tempurath', 'TriTerror', 'AceOfSwords', 'EldritchDisciple', 'TheElderDragon', 'DeathlockDreilak', 'TheAmethystGiant', 'Uvhash-Ka', 'EldritchMinion', 'Draxxius', 'BookOfSecrets', 'KeeperOfLore', 'EldritchGuardian', 'Netherhound', 'Ahrimas', 'CorruptMagus', 'VashDagon', 'WallOfTentacles', 'Medea', 'GelatinousCube', 'ZuulGoth', 'TomeOfEvil', 'Tzathoth', 'Hellspawn', 'Myzmer', 'VoidPortal', 'DarkTroll', 'SacrificialPriest', 'GreenSlime', 'Cthyryzyx', 'Ferit', 'Abhorath', 'AncientHorror', 'Warlock', 'Acolyte', 'Golem'],
  3009: ['KingElbormor', 'Siobhan', 'ElvenNoble', 'Cosmo', 'ImmortalSelene', 'CorruptedCrystalem', 'WoodRot', 'Leucithrax', 'GuardianSpirit', 'LioraMistveil', 'Mistlark', 'ArcaneSabercat', 'SirAiluin', 'CrystalEggs', 'HeraldOfKrystenax', 'Amethialas', 'FloraFawn', 'MoonMage', 'SwordMaiden', 'Tannenbaum', 'MoonPhoenix', 'TheMagician', 'Forgemistress', 'StarryMage', 'SapphireKnight', 'WillOfNysha', 'Grimcorn', 'LordEhrondil', 'SilverOak', 'Willow', 'Arcanus', 'Hind', 'QueenAurora', 'Wisp', 'Krystenax', 'TheSilvermaiden', 'PrincessElspeth', 'Unicorn', 'Enchantress', 'ElvenBard', 'Swordmaster', 'SilverDrakon'],
} as const satisfies Record<number, readonly string[]>;
export const rawKingdomPool = (id: keyof typeof RAW_KINGDOM_POOLS): string[] => [...RAW_KINGDOM_POOLS[id]];
