const R = 'tests/unit/gowLaneL4bB05Repro.test.ts';
export default [
  { id: 'L4b-7030-dragon', key: 'troop:7030', clause: "c1 'Convert all Red Gems into Yellow Dragon Gems.' / native ConvertGems Color2 DragonYellow", expected: 'Every Red gem becomes a Yellow dragonGem (special, spec.color Yellow)', actual: 'batch-r8 8557 = transform(Red, Yellow): plain Yellow gems', repro: `${R} > L4b-7030-dragon`, layer: 'assembler', status: 'open' },
  { id: 'L4b-7276-singlegem', key: 'troop:7276', clause: "c1 'Convert a chosen Mana Gem to an Uber Doomskull.' / native ConvertGems FromTarget BoardTarget SingleGem Amount 1", expected: 'Only the chosen cell becomes an Uber Doomskull', actual: "batch-r4 8901 = transformToSpecial(CHOSEN,...): converts ALL gems of a chosen colour", repro: `${R} > L4b-7276-singlegem`, layer: 'assembler', status: 'open', related: 'Same SingleGem-as-colour shape in troop:6111 (7181 CHOSEN), troop:7092 (8627 ANY), troop:7169 (8722 ANY), troop:7480 (9197 ANY), weapon:1067 (7174 ANY): re-check when they come up.' },
  { id: 'L4b-7195-order', key: 'troop:7195', clause: "native steps 0 ConvertGems Green->Skull, 1 CauseHuntersMark FrontEnemy", expected: 'R001: conversion (and its skull cascade) resolves before Hunter\'s Mark', actual: 'batch-36 8782 = inflict(marked, enemyFront) then transform', repro: `${R} > L4b-7195-order`, layer: 'assembler', status: 'open' },
  { id: 'L4b-6824-random-ally', key: 'troop:6824', clause: "c2 'Barrier and Submerge a random Ally.' / native 1 CauseBarrier RandomAlly, 2 CauseSubmerged FromPrevious", expected: 'A random living ally (no ally choice) gets Barrier, then the same ally Submerged', actual: 'batch-14 8234 uses allyChosen (submerged then barrier): needs a chosen ally, cast is refused without one; order reversed; zh says 一名盟友', repro: `${R} > L4b-6824-random-ally / L4b-6824-zh`, layer: 'assembler+data', status: 'open' },
  { id: 'L4b-6841-prefnotprev', key: 'troop:6841', clause: "c2 'Deal [Magic + 2] damage to 2 random Enemies.' / native Damage RandomEnemy + Damage RandomPrefNotPrevEnemy", expected: 'Two separate hits; the second prefers another enemy but falls back to the same one when only one is alive (2 hits)', actual: 'enemyRandomN n 2: distinct targets only, a lone enemy is hit once (same class as lane-L7 L7-7344; engine has enemyRandomPrefNotPrev)', repro: 'not yet (draft pending)', layer: 'assembler', status: 'open' },
  { id: 'L4b-7068-potion-colour', key: 'troop:7068', clause: "c1 'Convert 5 Green Gems to Purple Potions' / native Color2 PurpleManaPotion", expected: 'manaPotionGem with spec.color Purple', actual: "prototype toSpecial 'manaPotionGem' without colour", repro: 'not yet', layer: 'assembler', status: 'open' },
  { id: 'L4b-1548-missing-steps', key: 'weapon:1548', clause: "c1 'Convert all Red Gems to Cursed Gems and convert all Purple Gems to Doomskulls.'", expected: 'Red -> curseGem, then Purple -> doomSkull, then enemy team jumble', actual: 'prototype: Red -> doomSkull only (Purple conversion missing, Cursed Gem missing)', repro: 'not yet', layer: 'assembler', status: 'open' },
  { id: 'L4b-7270-dragon', key: 'troop:7270', clause: "c2 'Then create 3 Brown Dragon Gems.' / native CreateGems DragonBrown 3", expected: '3 Brown dragonGem specials', actual: 'prototype creates 3 plain Brown gems', repro: 'not yet', layer: 'assembler', status: 'open' },
  { id: 'L4b-7524-zh', key: 'troop:7524', clause: "c2 '... then convert all other skulls to Uber Doomskulls.'", expected: 'Chinese says 超级末日骷髅头', actual: "Chinese '再将其他的骷髅头转换成末日骷髅头' (drops Uber)", repro: 'not yet', layer: 'data', status: 'open' },
  { id: 'L4b-chosen-any', key: 'weapon:1625', clause: "c1 'Convert all Gems of a chosen Color into Decaying Gems.' / native ConvertGems Color1 FromTarget", expected: 'Only gems of the chosen colour convert', actual: "prototype transform from 'ANY': every non-target gem on the board converts", repro: 'not yet', layer: 'assembler', status: 'open', related: 'weapon:1674 (9831 Bleed Gems, same ANY shape; also FromManaColorEnemy status targets)' },
  { id: 'L4b-chosen-colour-exclusion', key: 'troop:6124', clause: "native spell Target Not<X>OrSkullGems (e.g. 7216 NotGreenOrSkullGems) for 'Transform a selected Mana color to X'", expected: 'The chosen colour can never be X (or Skull); AI never picks the target colour', actual: 'AiColorChooser picks the most common colour regardless of the native Target restriction (can pick X: a Green->Green no-op); the player palette (App.ts) has no restriction either', repro: 'not yet', layer: 'primitive+ui', status: 'open', affects: ['troop:6124', 'troop:6256', 'troop:6399', 'troop:6824', 'troop:6216', 'troop:6987', 'troop:7705'] },
  { id: 'L4b-strongest-metric', key: 'troop:6805', clause: 'native StrongestAlly / StrongestEnemy / WeakestEnemy / TwoStrongestEnemies targets', expected: 'Metric confirmed by a stored source', actual: 'Runtime: strongest = highest current hp, weakest = lowest hp (armor ignored; spell-rules.md). Only source found (ingested gold-primary-sources/community-2018-08-02-weakest-life-plus-armor.json) is a single community answer saying Life + Armor summed.', layer: 'primitive', status: 'source-dispute', affects: ['troop:6805', 'troop:6842', 'troop:6955', 'troop:6565', 'troop:6592', 'troop:7410', 'troop:6771'], sourceDispute: { urls: ['https://community.gemsofwar.com/t/what-does-weakest-mean/43465'], level: 'community forum, one answer, no developer', recommendation: 'coordinator ruling (hp vs hp+armor, tie-break); ~70 native steps use these targets' } },
];
