import { dims, main, RULE_STATUS, RULE_FROZEN, R001, R002, R004, R006 } from './spec-lib.mjs';
const test = 'tests/unit/gowLaneL3B03.test.ts';
const FROZEN = { id: 'frozen', role: 'official-shared-rule', path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' };
export default {
  'troop:6252': {
    decision: 'accept', test,
    en: 'troop:6252 DRACOS-1337 SpellId 7395, cost 15, Yellow/Purple; "Silence, Stun, and drain [Magic + 1] Mana from an enemy, with a 30% chance to destroy them."',
    native: 'Spell 7395 Cost 15 Target Enemy; CauseStun -> CauseSilence -> DecreaseMana Amount 1 SPM 1 -> LethalDamage PercentageChance 30 (all FromTarget).',
    rule: { path: RULE_STATUS, note: 'Stun disables traits; Blessed immune to statuses and blocks Mana Drain.' },
    extra: [R001, R004, R006],
    dims: dims({
      id: ['v', 'troop:6252 -> 7395, cost 15, Yellow/Purple.'],
      target: ['v', 'Chosen enemy only; others never touched or destroyed.'],
      formula: ['v', 'Drain Magic+1 (20 -> 19 / 9), clamped at 0.'],
      cond: ['v', '30% destroy: 60 seeds give 8..30 destructions of a full-Life target (hp 0, defeated).'],
      status: ['v', 'Stun and Silence on the chosen enemy; Blessed blocks; R004 durations (convention:R006-C2).'],
      order: ['v', 'FIXED L3-011: Stun before Silence (R001), then drain, then the chance to destroy.'],
      mana: ['v', 'Drain only (caster not refilled); turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Silence, Stun, drain [Magic+1], 30% destroy.'] },
    steps: { 0: ['v', 'CauseStun FromTarget.'], 1: ['v', 'CauseSilence FromTarget.'], 2: ['v', 'DecreaseMana Magic+1.'], 3: ['v', 'LethalDamage 30%.'] },
    branches: main('Destroy / survive both observed over seeds.'),
  },
  'troop:7100': {
    decision: 'accept', test,
    en: 'troop:7100 Stoneborn Lion SpellId 8635, cost 11, Blue/Brown; "Deal [Magic + 3] damage to an Enemy, and Stun them. If the Enemy dies, create 2 Elemental Stars and gain an extra turn."',
    native: 'Spell 8635 Cost 11 Target Enemy; CauseStun FromTarget -> Damage 3 SPM 1 -> CreateGems ElementalStar 2 AddForKill -> ExtraTurnConditional AddForKill.',
    rule: { path: RULE_STATUS, note: 'Stun definition; Barrier blocks one damage instance.' },
    extra: [R001, R004, R006, FROZEN],
    dims: dims({
      id: ['v', 'troop:7100 -> 8635, cost 11, Blue/Brown.'],
      target: ['v', 'Chosen enemy only.'],
      formula: ['v', 'Magic+3.'],
      cond: ['v', 'AddForKill: kill -> 2 stars + extra turn; survivor/Barrier -> neither.'],
      status: ['v', 'Stun on chosen enemy first; R004 (convention:R006-C2).'],
      gems: ['v', 'Exactly 2 Elemental Stars on kill.'],
      order: ['v', 'FIXED L3-001: CauseStun before Damage (R001).'],
      mana: ['v', 'Kill -> skill extra turn; frozen caster -> none; survivor -> switched.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Stun + [Magic+3].'], c2: ['v', 'Kill -> 2 stars + extra turn.'] },
    steps: { 0: ['v', 'CauseStun first.'], 1: ['v', 'Damage Magic+3.'], 2: ['v', 'CreateGems ElementalStar AddForKill.'], 3: ['v', 'ExtraTurnConditional AddForKill.'] },
    branches: main('Kill / no-kill tested.'),
  },
  'troop:6225': {
    decision: 'accept', test,
    en: 'troop:6225 Manticore SpellId 7367, cost 9, Green/Yellow; "Stun an enemy and drain their Mana by 7. Gain [Magic + 1] Attack."',
    native: 'Spell 7367 Cost 9 Target Enemy; CauseStun FromTarget -> DecreaseMana FromTarget 7 (no SPM) -> IncreaseAttack Self 1 SPM 1.',
    rule: { path: RULE_STATUS, note: 'Stun disables traits; Blessed blocks statuses and Mana Drain; Entangle blocks Attack boosts.' },
    extra: [R004, R006],
    dims: dims({
      id: ['v', 'troop:6225 -> 7367, cost 9, Green/Yellow.'],
      target: ['v', 'Chosen enemy; caster for Attack.'],
      formula: ['v', 'Fixed 7 drain (clamped at 0); Attack +Magic+1.'],
      status: ['v', 'Stun on chosen; Blessed blocks; R004.'],
      order: ['v', 'Stun -> drain -> Attack matches native; Stun first bypasses Mana Shield (drained 20 -> 13).'],
      mana: ['v', 'Drain only, caster mana 0; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Stun + drain 7.'], c2: ['v', 'Gain [Magic+1] Attack (0 while Entangled).'] },
    steps: { 0: ['v', 'CauseStun FromTarget.'], 1: ['v', 'DecreaseMana 7 fixed.'], 2: ['v', 'IncreaseAttack Self Magic+1.'] },
    branches: main('Single branch.'),
  },
  'troop:7418': {
    decision: 'accept', test,
    en: 'troop:7418 Void Manticore SpellId 9067, cost 12, Blue/Yellow; "Inflict Terror on an Enemy. Then steal [Magic + 1] Attack, and drain their Mana by 7."',
    native: 'Spell 9067 Cost 12 Target Enemy; CauseTerror FromTarget -> StealAttack FromTarget 1 SPM 1 -> DecreaseMana FromTarget 7 (no SPM).',
    rule: { path: RULE_STATUS, note: 'Terror definition.' },
    extra: [R004, R006],
    dims: dims({
      id: ['v', 'troop:7418 -> 9067, cost 12, Blue/Yellow.'],
      target: ['v', 'Chosen enemy only; others untouched.'],
      formula: ['v', 'Steal Magic+1 Attack (clamped to target Attack: 3 -> caster +3); FIXED L3-008 drain fixed 7 (not 7+Magic).'],
      status: ['v', 'Terror on chosen; R004 (convention:R006-C2).'],
      order: ['v', 'Terror -> steal -> drain matches native.'],
      mana: ['v', 'Drain only; caster mana 0; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Terror on the chosen enemy.'], c2: ['v', 'Steal [Magic+1] Attack, drain 7.'] },
    steps: { 0: ['v', 'CauseTerror.'], 1: ['v', 'StealAttack Magic+1.'], 2: ['v', 'DecreaseMana 7 fixed.'] },
    branches: main('Single branch.'),
  },
  'troop:7796': {
    decision: 'draft', test,
    en: 'troop:7796 Jellymaid SpellId 9816, cost 12, Purple/Brown; "Cleanse and Submerge 2 random Allies, and give them half their Mana."',
    native: 'Spell 9816 Cost 12 Target None; Cleanse RandomAlly -> CauseSubmerged FromPrevious -> GenerateHalfMana FromPrevious -> Cleanse RandomPrefNotPrevAlly -> CauseSubmerged FromPrevious -> GenerateHalfMana FromPrevious.',
    rule: { path: RULE_STATUS, note: 'Submerged definition; Silence prevents mana gain.' },
    extra: [R002, R004],
    dims: dims({
      id: ['v', 'troop:7796 -> 9816, cost 12, Purple/Brown.'],
      target: ['v', 'FIXED L3-012: second triple prefers a different ally (allyRandomPrefNotPrev); lone caster -> reused.'],
      formula: ['disputed', 'L3-005 source-dispute: half of an odd mana cost (floor) unsourced; even costs verified.'],
      status: ['v', 'Cleanse removes negatives only (R002), then Submerged (R004: removed when the holder acts).'],
      order: ['v', 'Cleanse -> Submerge -> half mana per ally, twice, as native.'],
      mana: ['v', 'Each chosen ally +half its bar (lone caster 6+6 = 12); silenced ally cleansed before the grant; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['disputed', 'Targets / cleanse / submerge verified; odd-cost half-mana rounding disputed (L3-005).'] },
    steps: { 0: ['v', 'Cleanse RandomAlly.'], 1: ['v', 'CauseSubmerged FromPrevious.'], 2: ['disputed', 'GenerateHalfMana (odd cost rounding L3-005).'], 3: ['v', 'Cleanse RandomPrefNotPrevAlly.'], 4: ['v', 'CauseSubmerged FromPrevious.'], 5: ['disputed', 'GenerateHalfMana (L3-005).'] },
    branches: main('Single branch.'),
  },
};
