import { dims, main, RULE_STATUS, RULE_FROZEN, R002, R004, R006 } from './spec-lib.mjs';
const test = 'tests/unit/gowLaneL3B04.test.ts';
const FROZEN = { id: 'frozen', role: 'official-shared-rule', path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' };
const GEMS = { id: 'gems', role: 'official-shared-rule', path: 'artifacts/gow-skill-audit/gold-primary-sources/official-heroic-gems-freshdesk.html', note: 'Special gem definitions (Gargoyle, Burning, Doomskull, Bomb).' };
export default {
  'troop:6518': {
    decision: 'accept', test,
    en: 'troop:6518 Sister Superior SpellId 7710, cost 6, Green/Yellow; "Cleanse all Allies. Dispel and Stun Daemon and Undead Enemies. Gain an extra turn."',
    native: 'Spell 7710 Cost 6 Target None; Cleanse AllAllies -> Dispel EnemyType daemon -> Dispel EnemyType undead -> CauseStun EnemyType daemon -> CauseStun EnemyType undead -> ExtraTurn Self.',
    rule: { path: RULE_STATUS, note: 'Cleanse removes negatives; Dispel removes positives; Stun definition.' },
    extra: [R002, R004, R006, FROZEN],
    dims: dims({
      id: ['v', 'troop:6518 -> 7710, cost 6, Green/Yellow.'],
      target: ['v', 'All allies cleansed; only Daemon / Undead enemies dispelled and stunned (a Daemon+Undead troop once).'],
      cond: ['v', 'Race filter Daemon OR Undead; no such enemy -> only cleanse + extra turn.'],
      status: ['v', 'Cleanse keeps Barrier (R002); Dispel removes Barrier/Enchanted/Reflect/Blessed etc. before Stun (a Blessed Daemon is stunned); R004 durations.'],
      order: ['v', 'Cleanse -> Dispel -> Stun -> ExtraTurn matches native (daemon/undead split steps equivalent to one filtered segment).'],
      mana: ['v', 'Unconditional skill extra turn; a Frozen caster is cleansed at step 0 and therefore still gains it (native order).'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'All allies cleansed (negatives only).'], c2: ['v', 'Daemon/Undead enemies dispelled + stunned.'], c3: ['v', 'Extra turn.'] },
    steps: { 0: ['v', 'Cleanse AllAllies.'], 1: ['v', 'Dispel daemon.'], 2: ['v', 'Dispel undead.'], 3: ['v', 'CauseStun daemon.'], 4: ['v', 'CauseStun undead.'], 5: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
  'troop:6319': {
    decision: 'draft', test,
    en: 'troop:6319 Sentry Bot SpellId 7469, cost 10, Yellow; "Cleanse all other Allies, and give 3-8 Mana to them. Create 3 Bomb Gems."',
    native: 'Spell 7469 Cost 10 Target None; Cleanse AllAlliesButNotSelf -> GenerateRandomMana AllAlliesButNotSelf Amount 8 -> CreateGems Bomb 3.',
    rule: { path: RULE_STATUS, note: 'Cleanse removes negatives (Silence lifted before mana).' },
    extra: [R002, GEMS],
    dims: dims({
      id: ['v', 'troop:6319 -> 7469, cost 10, Yellow.'],
      target: ['v', 'Other allies only (caster excluded).'],
      formula: ['disputed', 'L3-013 source-dispute: one shared 3..8 roll for all recipients (runtime) vs independent rolls per ally; range 3..8 and cap verified.'],
      status: ['v', 'Cleanse other allies (Silence removed before the grant).'],
      gems: ['v', '3 Bomb Gems created.'],
      order: ['v', 'Cleanse -> mana -> bombs matches native.'],
      mana: ['v', 'Recipients gain 3..8 capped at manaCost; caster 0; no extra turn.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['disputed', 'Cleanse verified; roll scope disputed (L3-013).'], c2: ['v', '3 Bomb Gems.'] },
    steps: { 0: ['v', 'Cleanse AllAlliesButNotSelf.'], 1: ['disputed', 'GenerateRandomMana roll scope (L3-013).'], 2: ['v', 'CreateGems Bomb 3.'] },
    branches: main('Single branch.'),
  },
  'troop:7361': {
    decision: 'accept', test,
    en: 'troop:7361 Geryon SpellId 9001, cost 20, Yellow/Brown; "Convert Green Gems to Blue, and convert Purple Gems to Doomskulls. Drain 2 Mana from all Enemies."',
    native: 'Spell 9001 Cost 20 Target None; ConvertGems Green->Blue 100 -> ConvertGems Purple->Doomskull 100 -> DecreaseMana AllEnemies 2 (no SPM).',
    rule: { path: RULE_STATUS, note: 'Blessed blocks Mana Drain.' },
    extra: [GEMS],
    dims: dims({
      id: ['v', 'troop:7361 -> 9001, cost 20, Yellow/Brown.'],
      target: ['v', 'All living enemies drained.'],
      formula: ['v', 'Fixed drain 2 (magic 0/10 same), clamped at 0.'],
      gems: ['v', 'All 16 Green -> Blue, all 16 Purple -> Doomskull; none when absent.'],
      order: ['v', 'Green->Blue, Purple->Doomskull, drain matches native.'],
      mana: ['v', 'Drain only; Blessed / Mana Shield keep mana; caster 0; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Both conversions.'], c2: ['v', 'Drain 2 from all enemies.'] },
    steps: { 0: ['v', 'ConvertGems Green->Blue.'], 1: ['v', 'ConvertGems Purple->Doomskull.'], 2: ['v', 'DecreaseMana 2.'] },
    branches: main('Single branch.'),
  },
  'troop:7486': {
    decision: 'accept', test,
    en: 'troop:7486 Groevanga SpellId 9219, cost 24, Blue/Yellow/Brown; "Convert all Gems of a chosen Color to Good Gargoyle Gems. Deal [(Magic x 1.5) + 4] damage to all Enemies of that Mana Color. Gain an extra turn."',
    native: 'Spell 9219 Cost 24 Target ManaGemsOnly; ConvertGems FromTarget->GoodGargoyle 100 -> Damage FromManaColorEnemy 4 SPM 1.5 -> ExtraTurn Self.',
    rule: { path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' },
    extra: [R006, GEMS],
    dims: dims({
      id: ['v', 'troop:7486 -> 9219, cost 24, Blue/Yellow/Brown.'],
      target: ['v', 'Chosen colour; damage only enemies whose mana colours include it (10 and 12 for Purple).'],
      formula: ['v', 'round(Magic x 1.5 + 4) (convention:R006-C1): magic 0/3/10 -> 4/9/19.'],
      cond: ['v', 'Colour with no matching enemy -> no damage.'],
      gems: ['v', 'All 16 chosen-colour gems -> gargoyleGem, Good tier (tier 1 / untiered = Good).'],
      order: ['v', 'Convert -> damage -> extra turn matches native.'],
      mana: ['v', 'Unconditional skill extra turn; frozen caster -> none.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Chosen colour -> Good Gargoyles.'], c2: ['v', 'Damage to enemies of that colour.'], c3: ['v', 'Extra turn.'] },
    steps: { 0: ['v', 'ConvertGems FromTarget->GoodGargoyle.'], 1: ['v', 'Damage FromManaColorEnemy 1.5M+4.'], 2: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
  'troop:7400': {
    decision: 'accept', test,
    en: 'troop:7400 Cinderhand Goblin SpellId 9050, cost 10, Red/Yellow; "Convert 5 Green Gems to Burning Gems. Gain an extra turn."',
    native: 'Spell 9050 Cost 10 Target None; ConvertGems Green->Burning Amount 5 -> ExtraTurn Self.',
    rule: { path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' },
    extra: [GEMS],
    dims: dims({
      id: ['v', 'troop:7400 -> 9050, cost 10, Red/Yellow.'],
      target: ['v', 'Board only.'],
      formula: ['v', 'Fixed 5 (magic-independent); fewer Green -> all of them (3 -> 3, 0 -> 0).'],
      gems: ['v', 'Exactly 5 Green -> burningGem.'],
      order: ['v', 'Convert -> extra turn matches native.'],
      mana: ['v', 'Unconditional skill extra turn; frozen caster -> none.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', '5 Green -> Burning Gems.'], c2: ['v', 'Extra turn.'] },
    steps: { 0: ['v', 'ConvertGems Green->Burning 5.'], 1: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
};
