import { dims, main, RULE_STATUS, RULE_FROZEN, R001, R003, R006 } from './spec-lib.mjs';
const test = 'tests/unit/gowLaneL3B05.test.ts';
const FROZEN = { id: 'frozen', role: 'official-shared-rule', path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' };
const GEMS = { id: 'gems', role: 'official-shared-rule', path: 'artifacts/gow-skill-audit/gold-primary-sources/official-heroic-gems-freshdesk.html', note: 'Elemental Star / Doomskull definitions.' };
export default {
  'troop:6032': {
    decision: 'accept', test,
    en: 'troop:6032 Satyr SpellId 7032, cost 8, Green; "Steal 2 Armor from the last Enemy, and shift it to Magic, then deal [Magic + 4] damage. Gain an extra turn. [1:1]"',
    native: 'Spell 7032 Cost 8 Target None; CountArmor LastEnemy 100 -> CountMax 2 -> DecreaseArmor LastEnemy (counter) -> IncreaseSpellPower Self (counter) -> Damage LastEnemy 4 SPM 1 -> ExtraTurn Self.',
    rule: { path: RULE_STATUS, note: 'Web: Magic boosts do not apply while Webbed.' },
    extra: [R001, R003, FROZEN],
    dims: dims({
      id: ['v', 'troop:6032 -> 7032, cost 8, Green.'],
      target: ['v', 'Last living enemy (dead last -> next living last).'],
      formula: ['v', 'Damage Magic+4 using the Magic raised by the steal (armor 5, magic 10 -> 16 total, 3 absorbed by remaining armor).'],
      boost: ['v', '[1:1] = CountArmor 100% capped by CountMax 2: armor 5 -> 2, armor 1 -> 1, armor 0 -> 0.'],
      order: ['v', 'FIXED L3-017: steal before damage (R001; English "then deal").'],
      mana: ['v', 'Unconditional skill extra turn.'],
      display: ['v', 'zh lists damage first then the steal; runtime follows native/English order (display wording order only, values match).'],
    }),
    clauses: { c1: ['v', 'Steal up to 2 Armor -> Magic, then [Magic+4] to the last enemy.'], c2: ['v', 'Extra turn.'], c3: ['v', '[1:1] conversion ratio label.'] },
    steps: { 0: ['v', 'CountArmor LastEnemy 100%.'], 1: ['v', 'CountMax 2.'], 2: ['v', 'DecreaseArmor by counter.'], 3: ['v', 'IncreaseSpellPower by counter (0 while Webbed).'], 4: ['v', 'Damage LastEnemy Magic+4.'], 5: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
  'troop:6035': {
    decision: 'accept', test,
    en: 'troop:6035 Blade Dancer SpellId 7035, cost 11, Green/Yellow; "Deal [Magic + 4] scatter damage, boosted by all enemy Armor. Steal 4 Magic from a random Enemy. [2:1]"',
    native: 'Spell 7035 Cost 11 Target None; CountArmor AllEnemies 50 -> ScatterDamage AllEnemies 4 SPM 1 (counter) -> DelayUntilEffectsComplete -> ResetTargets -> StealMagic RandomEnemy 4.',
    rule: { path: RULE_STATUS, note: 'Scatter damage semantics shared rule.' },
    extra: [R003],
    dims: dims({
      id: ['v', 'troop:6035 -> 7035, cost 11, Green/Yellow.'],
      target: ['v', 'Scatter over living enemies; random living enemy for the steal.'],
      formula: ['v', 'Scatter pool Magic+4 + floor(living enemy armor x 50%) (armor 9 -> +4), total removed asserted.'],
      boost: ['v', 'R003: [2:1] = CountArmor 50%.'],
      order: ['v', 'Count -> scatter -> steal matches native (Delay/ResetTargets are presentation).'],
      mana: ['v', 'FIXED L3-018: steals Magic (target 11 -> 7, caster +4, clamp to target Magic); no Mana moves; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Scatter [Magic+4] boosted by enemy armor.'], c2: ['v', 'Steal 4 Magic from a random enemy.'], c3: ['v', '[2:1] label.'] },
    steps: { 0: ['v', 'CountArmor AllEnemies 50%.'], 1: ['v', 'ScatterDamage Magic+4+counter.'], 2: ['v', 'DelayUntilEffectsComplete: scatter fully resolves before the steal (steal sees post-damage state; tested).'], 3: ['v', 'ResetTargets: the steal picks a fresh random living enemy (enemyRandom, independent of scatter targets; tested).'], 4: ['v', 'StealMagic RandomEnemy 4.'] },
    branches: main('Single branch.'),
  },
  'troop:6427': {
    decision: 'accept', test,
    en: 'troop:6427 Queen Titania SpellId 7600, cost 16, Red/Purple; "Deal [Magic + 2] damage to all enemies, boosted by Red enemies and allies. If there are 13 or more Red Gems, gain an extra turn. [x4]"',
    native: 'Spell 7600 Cost 16 Target None; CountArmyColor AllAllies Red 400 -> CountArmyColor AllEnemies Red 400 (counter) -> Damage AllEnemies 2 SPM 1 (counter) -> ExtraTurnConditional AddFor10RedGems.',
    rule: { path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' },
    extra: [R003],
    dims: dims({
      id: ['v', 'troop:6427 -> 7600, cost 16, Red/Purple.'],
      target: ['v', 'All living enemies.'],
      formula: ['v', 'Magic+2 + 4 x (living Red allies incl. caster + living Red enemies); armor absorbs first.'],
      boost: ['v', '[x4] multiplier; dead Red troops not counted.'],
      cond: ['v', 'R003: 13 Red -> extra turn, 12 -> none.'],
      order: ['v', 'Counts -> damage -> extra turn matches native.'],
      mana: ['v', 'Skill extra turn on 13+ Red; frozen caster none; otherwise switched.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Damage all, boosted x4 by Red allies and enemies.'], c2: ['v', '13+ Red -> extra turn.'], c3: ['v', '[x4] label.'] },
    steps: { 0: ['v', 'CountArmyColor AllAllies Red x4.'], 1: ['v', 'CountArmyColor AllEnemies Red x4 (accumulated).'], 2: ['v', 'Damage AllEnemies Magic+2+counter.'], 3: ['v', 'ExtraTurnConditional AddFor10RedGems = 13.'] },
    branches: main('Threshold both sides tested.'),
  },
  'troop:7198': {
    decision: 'draft', test,
    en: 'troop:7198 Natureborn Hunter SpellId 8785, cost 12, Blue/Green; "Create 1 Elemental Star, +1 more for every 3 Green Allies and +1 more for every 3 Green Gems. If the Enemy has a Beast, gain an extra turn. [3:1]"',
    native: 'Spell 8785 Cost 12 Target None; CountArmyColor AllAllies Green 34 -> CountGems Green 34 -> CreateGems ElementalStar 1 (counter) -> ExtraTurnConditional AddIfEnemyHasBeast.',
    rule: { path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' },
    extra: [R003, GEMS],
    dims: dims({
      id: ['v', 'troop:7198 -> 8785, cost 12, Blue/Green.'],
      target: ['v', 'Board / enemy race check only.'],
      boost: ['disputed', 'L3-014 source-dispute: runtime floors (Green allies + Green gems) x 34% once; native has two Count steps and English says +1 per 3 allies AND +1 per 3 gems (per-step floors). Values agree when either count is < 3 or the sum does not cross a boundary (tested 16 gems + 1 ally -> 6 stars).'],
      cond: ['v', 'Enemy Beast -> extra turn; none -> switched.'],
      gems: ['v', 'Elemental Stars created (1 base).'],
      order: ['v', 'Counts -> create -> extra turn matches native.'],
      mana: ['v', 'Skill extra turn only with an enemy Beast.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['disputed', 'Base 1 verified; per-source vs combined flooring disputed (L3-014).'], c2: ['v', 'Enemy Beast -> extra turn.'], c3: ['v', '[3:1] = 34% label (R003).'] },
    steps: { 0: ['disputed', 'CountArmyColor 34 (flooring scope L3-014).'], 1: ['disputed', 'CountGems 34 (flooring scope L3-014).'], 2: ['v', 'CreateGems ElementalStar 1 + counter.'], 3: ['v', 'ExtraTurnConditional AddIfEnemyHasBeast.'] },
    branches: main('Beast / no Beast tested.'),
  },
  'weapon:1226': {
    decision: 'accept', test,
    en: 'weapon:1226 Doomed Blade (gw_DoomedBlade) SpellId 7952, cost 18, Blue; "Deal [Magic + 3] damage to all Enemies, +1 per Tempering level. Transform Red Gems to Doomskulls, if the Enemy has a Doom, create 5 more. Gain 3 Mana for each Blue Enemy. [x3]"',
    native: 'Spell 7952 Cost 18 Target None; CountArmyColor AllEnemies Blue 300 -> Damage AllEnemies 3 SPM 1 AddForTempering 1 -> ConvertGems Red->Doomskull -> CreateGems Doomskull 5 AddIfEnemyHasDoom -> GenerateMana Self (counter).',
    rule: { path: 'artifacts/gow-skill-audit/gold-primary-sources/official-weapon-list.html', note: 'Weapon identity list.' },
    extra: [GEMS],
    dims: dims({
      id: ['v', 'weapon:1226 numeric 7952 and gw_DoomedBlade aliases, ReferenceName DoomedBlade, cost 18, Blue; weapons.json binding.'],
      target: ['v', 'All living enemies; Blue count over living enemies only.'],
      formula: ['v', 'Magic+3 + tempering level (0 -> +0, 2 -> +2).'],
      boost: ['v', '[x3] mana per Blue enemy (2 -> 6, 0 -> 0).'],
      cond: ['v', 'Enemy Doom -> 5 extra Doomskulls; none -> no creation.'],
      gems: ['v', 'FIXED L3-016: all Red -> Doomskull and +5 Doomskulls (never plain Skulls).'],
      order: ['v', 'Count -> damage -> convert -> create -> mana matches native.'],
      mana: ['v', 'FIXED L3-015: mana = 3 x Blue enemies only (no base 3); no extra turn.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Damage all +1 per Tempering.'], c2: ['v', 'Red -> Doomskulls; +5 Doomskulls if an enemy Doom.'], c3: ['v', '3 Mana per Blue enemy.'], c4: ['v', '[x3] label.'] },
    steps: { 0: ['v', 'CountArmyColor Blue x3.'], 1: ['v', 'Damage Magic+3 + tempering.'], 2: ['v', 'ConvertGems Red->Doomskull.'], 3: ['v', 'CreateGems Doomskull 5 AddIfEnemyHasDoom.'], 4: ['v', 'GenerateMana Self counter.'] },
    branches: main('Doom / no Doom tested.'),
  },
};
