import { dims, main, RULE_STATUS, RULE_FROZEN, R001, R003, R004, R006 } from './spec-lib.mjs';
const test = 'tests/unit/gowLaneL3B02.test.ts';
const FROZEN = { id: 'frozen', role: 'official-shared-rule', path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' };
export default {
  'troop:7099': {
    decision: 'accept', test,
    en: 'troop:7099 Waterborn Owl SpellId 8634, cost 11, Blue/Green; "Deal [Magic + 3] damage to an Enemy, and Freeze them. If the Enemy dies, create 2 Elemental Stars and gain an extra turn."',
    native: 'Spell 8634 Cost 11 Target Enemy; CauseFrozen FromTarget -> Damage Amount 3 SPM 1 -> CreateGems ElementalStar 2 AddForKill -> ExtraTurnConditional AddForKill.',
    rule: { path: RULE_STATUS, note: 'Frozen: no extra turns from matches/spells for that troop; Barrier blocks one damage instance.' },
    extra: [R001, R004, R006, FROZEN],
    dims: dims({
      id: ['v', 'troop:7099 -> 8634, cost 11, Blue/Green.'],
      target: ['v', 'Chosen enemy only.'],
      formula: ['v', 'Magic+3 at magic 0 / 10.'],
      cond: ['v', 'AddForKill: kill -> stars + extra turn; survivor / Barrier -> neither.'],
      status: ['v', 'Frozen on the chosen enemy before damage; duration R004 (convention:R006-C2).'],
      gems: ['v', 'Elemental Stars created only on kill (gem-create/transform present on kill, none otherwise).'],
      order: ['v', 'FIXED L3-001: CauseFrozen before Damage (R001).'],
      mana: ['v', 'Kill -> skill extra turn kept; survivor -> switched; frozen caster -> no spell extra turn.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Freeze + [Magic+3] to chosen enemy.'], c2: ['v', 'Kill -> 2 stars + extra turn.'] },
    steps: { 0: ['v', 'CauseFrozen FromTarget first.'], 1: ['v', 'Damage Magic+3.'], 2: ['v', 'CreateGems ElementalStar AddForKill.'], 3: ['v', 'ExtraTurnConditional AddForKill.'] },
    branches: main('Kill / no-kill tested.'),
  },
  'troop:6113': {
    decision: 'accept', test,
    en: 'troop:6113 Dire Wolf SpellId 7205, cost 8, Green; "Entangle and Hunter\'s Mark the first Enemy. Deal [Magic + 2] damage to them. If there are 13 or more Green Gems, gain an extra turn."',
    native: 'Spell 7205 Cost 8 Target None; CauseHuntersMark FrontEnemy -> CauseEntangle FrontEnemy -> Damage FrontEnemy Amount 2 SPM 1 -> ExtraTurnConditional AddFor10GreenGems 100.',
    rule: { path: RULE_STATUS, note: "Entangle / Hunter's Mark definitions." },
    extra: [R001, R003, R004, R006, FROZEN],
    dims: dims({
      id: ['v', 'troop:6113 -> 7205, cost 8, Green.'],
      target: ['v', 'First living enemy (dead front skipped -> next).'],
      formula: ['v', 'Magic+2 (magic 0 -> 2, 10 -> 12).'],
      cond: ['v', 'R003: 13 Green -> extra turn, 12 -> none; 16 -> extra turn.'],
      status: ['v', "Entangle + Hunter's Mark (marked) on the front enemy; durations R004 (convention:R006-C2)."],
      order: ['v', 'R001 equivalence: prototype Entangle->Mark vs native Mark->Entangle is unobservable (independent statuses on the same target, both land; test proves both present); damage after statuses as native.'],
      mana: ['v', 'Extra turn is source skill; activePlayer kept; 12 Green -> switched; frozen caster -> no spell extra turn.'],
      display: ['v', 'zh matches (TROOPS single-spaced).'],
    }),
    clauses: { c1: ['v', 'Front enemy Entangled + Marked.'], c2: ['v', '[Magic+2] damage to front enemy.'], c3: ['v', '13+ Green -> extra turn.'] },
    steps: { 0: ['v', 'CauseHuntersMark FrontEnemy.'], 1: ['v', 'CauseEntangle FrontEnemy (order-equivalent).'], 2: ['v', 'Damage FrontEnemy Magic+2.'], 3: ['v', 'ExtraTurnConditional AddFor10GreenGems = 13.'] },
    branches: main('Threshold both sides tested.'),
  },
  'troop:7070': {
    decision: 'accept', test,
    en: 'troop:7070 Sky Scorpion SpellId 8598, cost 10, Green/Yellow; "Poison and drain 7 Mana from all Enemies. Then remove all Skulls. Can only be cast once."',
    native: 'Spell 8598 Cost 10 Target None; CausePoison AllEnemies -> DecreaseMana AllEnemies Amount 7 (no SPM) -> RemoveColor Skull 100 -> DisableMySpell Self.',
    rule: { path: RULE_STATUS, note: 'Poison never self-cures; Blessed blocks Mana Drain.' },
    extra: [R004, R006],
    dims: dims({
      id: ['v', 'troop:7070 -> 8598, cost 10, Green/Yellow.'],
      target: ['v', 'All living enemies poisoned and drained.'],
      formula: ['v', 'FIXED L3-008: fixed 7 drain (magic 0 and 10 identical), clamped at 0 (20/5/7/0 -> 13/0/0/0).'],
      cond: ['v', 'Once per battle: same troop refused on a second cast (mana kept, no log); FIXED L3-009 enemy casting the same spell does not disable mine.'],
      status: ['v', 'Poison (magnitude 3) on all enemies; no expiry (R004).'],
      gems: ['v', 'All 5 skulls removed (RemoveColor -> destroy skulls, project assembler convention shared by the RemoveColor family); none left.'],
      order: ['v', 'Poison -> drain -> remove skulls matches native.'],
      mana: ['v', 'FIXED L3-007: drain only, caster not refilled (mana 0); Blessed and Mana Shield enemies not drained; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'All enemies Poisoned and drained 7.'], c2: ['v', 'All skulls removed.'], c3: ['v', 'Second cast by the same troop refused.'] },
    steps: { 0: ['v', 'CausePoison AllEnemies.'], 1: ['v', 'DecreaseMana AllEnemies 7 fixed.'], 2: ['v', 'RemoveColor Skull.'], 3: ['v', 'DisableMySpell Self (per troop).'] },
    branches: main('Single branch; once-per-battle refusal tested.'),
  },
  'troop:6783': {
    decision: 'accept', test,
    en: 'troop:6783 Stringfiddler SpellId 8173, cost 14, Green/Purple; "Silence an Enemy. Explode [(Magic / 4) + 1] Gems of one of their Mana Colors. Gain an Extra Turn."',
    native: 'Spell 8173 Cost 14 Target Enemy; CauseSilence FromTarget -> ExplodeColor Color1 FromTarget Amount 1 SPM 0.25 -> ExtraTurn Self.',
    rule: { path: RULE_STATUS, note: 'Silence definition.' },
    extra: [R004, R006, FROZEN],
    dims: dims({
      id: ['v', 'troop:6783 -> 8173, cost 14, Green/Purple.'],
      target: ['v', 'Chosen enemy silenced; its mana colour selects the gems (Blue enemy -> Blue).'],
      formula: ['v', 'Explode count round(Magic x 0.25 + 1) (convention:R006-C1): magic 0/2/6/10/30 -> 1/2/3/4/6 (capped by 6 on board).'],
      status: ['v', 'Silence on chosen enemy only; duration R004.'],
      gems: ['v', 'Explode = centre + 8-neighbour ring; exactly N isolated Red centres exploded.'],
      order: ['v', 'Silence -> explode -> extra turn matches native.'],
      mana: ['v', 'Unconditional skill extra turn; frozen caster -> none.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Chosen enemy silenced.'], c2: ['v', '[(Magic/4)+1] gems of its colour exploded.'], c3: ['v', 'Extra turn.'] },
    steps: { 0: ['v', 'CauseSilence FromTarget.'], 1: ['v', 'ExplodeColor FromTarget SPM 0.25 +1.'], 2: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
  'troop:6481': {
    decision: 'accept', test,
    en: 'troop:6481 Champion of Anu SpellId 7668, cost 22, Blue/Red/Yellow; "Silence, Stun and drain all Mana from an enemy. Deal [Magic + 6] damage to them, and all enemies below them."',
    native: 'Spell 7668 Cost 22 Target Enemy; CauseStun -> CauseSilence -> DecreaseMana 100 (FromTarget) -> Damage FromTarget 6 SPM 1 -> Damage BelowTarget 6 SPM 1.',
    rule: { path: RULE_STATUS, note: 'Stun disables traits; Blessed immune to statuses and blocks Mana Drain.' },
    extra: [R001, R004, R006],
    dims: dims({
      id: ['v', 'troop:6481 -> 7668, cost 22, Blue/Red/Yellow.'],
      target: ['v', 'Chosen + all living enemies below (11 -> 11/12/13; 13 -> 13 only; dead skipped).'],
      formula: ['v', 'Magic+6 each; armor absorbs first.'],
      status: ['v', 'Stun + Silence on chosen; Blessed blocks both; R004 durations.'],
      order: ['v', 'FIXED L3-010: Stun -> Silence -> drain (R001): Stun disables Mana Shield so the shield-bearer is drained. Native two Damage steps = one enemyChosenAndBelow all-range segment (same set, same amount).'],
      mana: ['v', 'Chosen drained to 0, others keep mana; caster not refilled; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Silence, Stun, drain all Mana of the chosen enemy.'], c2: ['v', '[Magic+6] to it and all below.'] },
    steps: { 0: ['v', 'CauseStun FromTarget.'], 1: ['v', 'CauseSilence FromTarget.'], 2: ['v', 'DecreaseMana 100 = drain all.'], 3: ['v', 'Damage FromTarget Magic+6.'], 4: ['v', 'Damage BelowTarget Magic+6.'] },
    branches: main('Single branch.'),
  },
};
