import { dims, main, RULE_STATUS, RULE_FROZEN, R001, R003, R004, R006, R002 } from './spec-lib.mjs';
const test = 'tests/unit/gowLaneL3B01.test.ts';
const star = (key, spell, id, st, stName, cause, colours) => ({
  decision: 'accept', test,
  en: `${key} SpellId ${spell}, cost 11, ${colours}; "Deal [Magic + 3] damage to an Enemy, and ${stName} them. If the Enemy dies, create 2 Elemental Stars and gain an extra turn."`,
  native: `Spell ${spell} Cost 11 Target Enemy; ${cause} FromTarget -> Damage FromTarget Amount 3 SPM 1 -> CreateGems ElementalStar StatusAmount 2 AddForKill -> ExtraTurnConditional Self AddForKill 100.`,
  rule: { path: RULE_STATUS, note: `${stName === 'Burn' ? 'Burning: 3 damage per turn, armor first' : 'Entangle: Attack 0 while applied'}; Barrier blocks one damage instance.` },
  extra: [R001, R004, R006, { id: 'frozen', role: 'official-shared-rule', path: RULE_FROZEN, note: 'Frozen caster: no spell extra turn.' }],
  dims: dims({
    id: ['v', `troop:${id} -> spell ${spell}, ManaCost 11, colours ${colours}; TROOPS binding and native Cost equal.`],
    target: ['v', 'Chosen enemy only (enemyChosen); other enemies untouched; FixedTargetChooser 12 on both sides.'],
    formula: ['v', 'Damage Magic+3 (magic 0 -> 3, magic 10 -> 13); armor absorbs first.'],
    cond: ['v', 'AddForKill: stars + extra turn only when the damaged enemy dies (Life 3 at magic 0 dies; Life 4 / Barrier survive -> neither).'],
    status: ['v', `${st} applied to the chosen enemy (status-apply), duration per R004 (convention:R006-C2 Cause* Amount ignored)${st === 'burning' ? '; burning ticks 3 at the victim turn start' : ''}; Barrier does not block the status.`],
    gems: ['v', 'Exactly 2 elementalStar special gems created on kill, none otherwise.'],
    order: ['v', 'FIXED L3-001: native Cause* precedes Damage (R001): status-apply before skill-damage; a killed enemy still receives the status. ifTargetDied keyed on the damage segment.'],
    mana: ['v', 'Mana to 0 on cast; on kill skill extra turn (source skill), activePlayer kept, outcome extra-turn; survivor -> switched; frozen caster kill -> no spell extra turn.'],
    display: ['v', 'zh description matches (damage, status, 2 elemental stars, extra turn on death).'],
  }),
  clauses: { c1: ['v', `Chosen enemy gets ${st} then [Magic+3] damage.`], c2: ['v', 'On kill: 2 Elemental Stars + extra turn; no kill -> neither.'] },
  steps: { 0: ['v', `${cause} FromTarget = chosen enemy, first.`], 1: ['v', 'Damage Magic+3 on the chosen enemy.'], 2: ['v', 'CreateGems ElementalStar x2 AddForKill.'], 3: ['v', 'ExtraTurnConditional AddForKill.'] },
  branches: main('Kill / no-kill paths both tested.'),
});
export default {
  'troop:7313': {
    decision: 'draft', test,
    en: 'troop:7313 Relic Knight SpellId 8925, cost 12, Blue/Green; "Barrier an Ally, and give them Mana equal to half their Mana cost. If they are a Knight, create 3 Spirit Gems."',
    native: 'Spell 8925 Cost 12 Target Ally; CauseBarrier FromTarget -> GenerateHalfMana FromTarget -> CreateGems Spirit StatusAmount 3 AddForKnight.',
    rule: { path: RULE_STATUS, note: 'Barrier until one damage instance; Silence prevents gaining any mana.' },
    extra: [R002, R004],
    dims: dims({
      id: ['v', 'troop:7313 -> 8925, cost 12, Blue/Green.'],
      target: ['v', 'Chosen ally (incl. self) receives Barrier and mana; others untouched.'],
      formula: ['disputed', 'L3-005 source-dispute: half of an odd mana cost (floor per DECISIONS.md) has no English/native/official rounding source; even costs verified (12 -> 6).'],
      cond: ['v', 'AddForKnight: Knight ally -> 3 Spirit Gems; non-Knight -> none.'],
      status: ['v', 'Barrier on chosen ally, no expiry (R002).'],
      gems: ['disputed', 'L3-006 source-dispute: native Color1 Spirit has no colour; project creates Purple Spirit Gems.'],
      order: ['v', 'Barrier -> mana -> gems matches native order.'],
      mana: ['v', 'Caster pays 12; ally +half cost capped at manaCost; FIXED L3-004 silenced ally gains 0; turn passes.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['disputed', 'Barrier verified; half-mana rounding for odd costs disputed (L3-005).'], c2: ['disputed', 'Knight condition verified; Spirit colour disputed (L3-006).'] },
    steps: { 0: ['v', 'CauseBarrier FromTarget.'], 1: ['disputed', 'GenerateHalfMana: even cost verified, odd cost rounding L3-005.'], 2: ['disputed', 'CreateGems Spirit AddForKnight: colour L3-006.'] },
    branches: main('Knight / non-Knight paths tested.'),
  },
  'troop:7098': star('troop:7098 Fireborn Eagle', 8633, 7098, 'burning', 'Burn', 'CauseBurning', 'Red/Yellow'),
  'troop:7097': star('troop:7097 Natureborn Wolf', 8632, 7097, 'entangle', 'Entangle', 'CauseEntangle', 'Green/Red'),
  'troop:6285': {
    decision: 'accept', test,
    en: 'troop:6285 Frostling SpellId 7431, cost 8, Blue; "Freeze and Web an Enemy. If there are 13 or more Blue Gems, gain 4 Mana."',
    native: 'Spell 7431 Cost 8 Target Enemy; CauseFrozen FromTarget -> CauseWeb FromTarget -> GenerateMana Self StatusAmount 4 AddFor10BlueGems.',
    rule: { path: RULE_STATUS, note: 'Frozen blocks extra turns / Web sets Magic to 0.' },
    extra: [R003, R004, R006],
    dims: dims({
      id: ['v', 'troop:6285 -> 7431, cost 8, Blue.'],
      target: ['v', 'FIXED L3-002: chosen enemy (native spell Target Enemy), tested targets 10 and 13; others untouched.'],
      formula: ['v', 'Fixed +4 Mana (StatusAmount 4), independent of Magic and of the mana bar (manaCost 12 case -> 4).'],
      cond: ['v', 'R003: 13 Blue -> +4, 12 Blue -> +0, 16 -> +4.'],
      status: ['v', 'Frozen then Web on the same chosen enemy; durations R004 (convention:R006-C2).'],
      order: ['v', 'Frozen -> Web -> mana matches native.'],
      mana: ['v', 'Caster pays 8 then +4 when 13+ Blue; no extra turn; turn passes.'],
      display: ['v', 'zh 「自身恢复一半的法力值」 equals the English 4 Mana for this cost-8 troop (half of 8); runtime uses the native fixed 4.'],
    }),
    clauses: { c1: ['v', 'Chosen enemy Frozen and Webbed.'], c2: ['v', '13+ Blue -> gain 4 Mana; 12 -> 0.'] },
    steps: { 0: ['v', 'CauseFrozen FromTarget (chosen).'], 1: ['v', 'CauseWeb FromTarget (lastTarget = chosen).'], 2: ['v', 'GenerateMana Self 4 AddFor10BlueGems (13).'] },
    branches: main('Threshold both sides tested.'),
  },
  'troop:7208': {
    decision: 'accept', test,
    en: 'troop:7208 Eternal Sentinel SpellId 8795, cost 11, Yellow/Purple; "Freeze a random Enemy. Create 3 Gargoyle Gems, and gain an extra turn."',
    native: 'Spell 8795 Cost 11 Target None; CauseFrozen RandomEnemy -> CreateGems2Colors GoodGargoyle/BadGargoyle Amount 3 -> ExtraTurn Self.',
    rule: { path: RULE_FROZEN, note: 'Frozen caster cannot gain a spell extra turn.' },
    extra: [R004, R006, { id: 'rl4b01', role: 'user-ruling', path: 'tasks/active/gow-skill-shards/rulings/RL4b-01-two-colour-overwrite.md', note: 'Two-colour create: each selected cell gets A or B.' }],
    dims: dims({
      id: ['v', 'troop:7208 -> 8795, cost 11, Yellow/Purple.'],
      target: ['v', 'One random living enemy Frozen; dead enemies skipped.'],
      status: ['v', 'Frozen on a random enemy, duration R004 (convention:R006-C2).'],
      gems: ['v', 'FIXED L3-003: exactly 3 gargoyle gems per cast, each tier 1 (Good) or 2 (Evil); both tiers observed over seeds (RL4b-01).'],
      order: ['v', 'Freeze -> create -> extra turn matches native.'],
      mana: ['v', 'Unconditional skill extra turn (activePlayer kept, outcome extra-turn); frozen caster -> none.'],
      display: ['v', 'zh matches.'],
    }),
    clauses: { c1: ['v', 'Random enemy Frozen.'], c2: ['v', '3 Good/Evil Gargoyle Gems + extra turn.'] },
    steps: { 0: ['v', 'CauseFrozen RandomEnemy.'], 1: ['v', 'CreateGems2Colors Good/Bad Gargoyle x3.'], 2: ['v', 'ExtraTurn Self.'] },
    branches: main('Single branch.'),
  },
};
